/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AppStoreResponseConfig } from './AppStoreResponseConfig.js';
import {
    AppStoreResponseConfigFromJSON,
    AppStoreResponseConfigFromJSONTyped,
    AppStoreResponseConfigToJSON,
    AppStoreResponseConfigToJSONTyped,
} from './AppStoreResponseConfig.js';

/**
 * App Store Reviews integration record
 * @export
 * @interface AppStoreIntegration
 */
export interface AppStoreIntegration {
    /**
     * 
     * @type {number}
     * @memberof AppStoreIntegration
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AppStoreIntegration
     */
    integrationId: AppStoreIntegrationIntegrationIdEnum;
    /**
     * 
     * @type {string}
     * @memberof AppStoreIntegration
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof AppStoreIntegration
     */
    organisationId: string;
    /**
     * 
     * @type {AppStoreResponseConfig}
     * @memberof AppStoreIntegration
     */
    config: AppStoreResponseConfig;
    /**
     * 
     * @type {Date}
     * @memberof AppStoreIntegration
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppStoreIntegration
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const AppStoreIntegrationIntegrationIdEnum = {
    AppStoreReviews: 'APP_STORE_REVIEWS'
} as const;
export type AppStoreIntegrationIntegrationIdEnum = typeof AppStoreIntegrationIntegrationIdEnum[keyof typeof AppStoreIntegrationIntegrationIdEnum];


/**
 * Check if a given object implements the AppStoreIntegration interface.
 */
export function instanceOfAppStoreIntegration(value: object): value is AppStoreIntegration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AppStoreIntegrationFromJSON(json: any): AppStoreIntegration {
    return AppStoreIntegrationFromJSONTyped(json, false);
}

export function AppStoreIntegrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreIntegration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'integrationId': json['integrationId'],
        'workspaceId': json['workspaceId'],
        'organisationId': json['organisationId'],
        'config': AppStoreResponseConfigFromJSON(json['config']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function AppStoreIntegrationToJSON(json: any): AppStoreIntegration {
    return AppStoreIntegrationToJSONTyped(json, false);
}

export function AppStoreIntegrationToJSONTyped(value?: AppStoreIntegration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'integrationId': value['integrationId'],
        'workspaceId': value['workspaceId'],
        'organisationId': value['organisationId'],
        'config': AppStoreResponseConfigToJSON(value['config']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

