/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerUpdateOpportunity agent
 * @export
 * @interface ConsiderUpdateOpportunityRequest
 */
export interface ConsiderUpdateOpportunityRequest {
    /**
     * ID of the opportunity to update
     * @type {string}
     * @memberof ConsiderUpdateOpportunityRequest
     */
    opportunityId: string;
    /**
     * List of insight IDs to inform the opportunity update
     * @type {Array<string>}
     * @memberof ConsiderUpdateOpportunityRequest
     */
    insightIds: Array<string>;
}

/**
 * Check if a given object implements the ConsiderUpdateOpportunityRequest interface.
 */
export function instanceOfConsiderUpdateOpportunityRequest(value: object): value is ConsiderUpdateOpportunityRequest {
    if (!('opportunityId' in value) || value['opportunityId'] === undefined) return false;
    if (!('insightIds' in value) || value['insightIds'] === undefined) return false;
    return true;
}

export function ConsiderUpdateOpportunityRequestFromJSON(json: any): ConsiderUpdateOpportunityRequest {
    return ConsiderUpdateOpportunityRequestFromJSONTyped(json, false);
}

export function ConsiderUpdateOpportunityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderUpdateOpportunityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityId': json['opportunityId'],
        'insightIds': json['insightIds'],
    };
}

export function ConsiderUpdateOpportunityRequestToJSON(json: any): ConsiderUpdateOpportunityRequest {
    return ConsiderUpdateOpportunityRequestToJSONTyped(json, false);
}

export function ConsiderUpdateOpportunityRequestToJSONTyped(value?: ConsiderUpdateOpportunityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityId': value['opportunityId'],
        'insightIds': value['insightIds'],
    };
}

