/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerOpportunitiesToOutcomes agent
 * @export
 * @interface ConsiderOpportunitiesToOutcomesRequest
 */
export interface ConsiderOpportunitiesToOutcomesRequest {
    /**
     * List of opportunity IDs to match to outcomes
     * @type {Array<string>}
     * @memberof ConsiderOpportunitiesToOutcomesRequest
     */
    opportunityIds: Array<string>;
}

/**
 * Check if a given object implements the ConsiderOpportunitiesToOutcomesRequest interface.
 */
export function instanceOfConsiderOpportunitiesToOutcomesRequest(value: object): value is ConsiderOpportunitiesToOutcomesRequest {
    if (!('opportunityIds' in value) || value['opportunityIds'] === undefined) return false;
    return true;
}

export function ConsiderOpportunitiesToOutcomesRequestFromJSON(json: any): ConsiderOpportunitiesToOutcomesRequest {
    return ConsiderOpportunitiesToOutcomesRequestFromJSONTyped(json, false);
}

export function ConsiderOpportunitiesToOutcomesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderOpportunitiesToOutcomesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityIds': json['opportunityIds'],
    };
}

export function ConsiderOpportunitiesToOutcomesRequestToJSON(json: any): ConsiderOpportunitiesToOutcomesRequest {
    return ConsiderOpportunitiesToOutcomesRequestToJSONTyped(json, false);
}

export function ConsiderOpportunitiesToOutcomesRequestToJSONTyped(value?: ConsiderOpportunitiesToOutcomesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityIds': value['opportunityIds'],
    };
}

