/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerInsightsFromFeedback agent
 * @export
 * @interface ConsiderInsightsFromFeedbackRequest
 */
export interface ConsiderInsightsFromFeedbackRequest {
    /**
     * The raw feedback text to process
     * @type {string}
     * @memberof ConsiderInsightsFromFeedbackRequest
     */
    rawFeedback: string;
    /**
     * Source of the feedback
     * @type {string}
     * @memberof ConsiderInsightsFromFeedbackRequest
     */
    source: string;
}

/**
 * Check if a given object implements the ConsiderInsightsFromFeedbackRequest interface.
 */
export function instanceOfConsiderInsightsFromFeedbackRequest(value: object): value is ConsiderInsightsFromFeedbackRequest {
    if (!('rawFeedback' in value) || value['rawFeedback'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function ConsiderInsightsFromFeedbackRequestFromJSON(json: any): ConsiderInsightsFromFeedbackRequest {
    return ConsiderInsightsFromFeedbackRequestFromJSONTyped(json, false);
}

export function ConsiderInsightsFromFeedbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderInsightsFromFeedbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rawFeedback': json['rawFeedback'],
        'source': json['source'],
    };
}

export function ConsiderInsightsFromFeedbackRequestToJSON(json: any): ConsiderInsightsFromFeedbackRequest {
    return ConsiderInsightsFromFeedbackRequestToJSONTyped(json, false);
}

export function ConsiderInsightsFromFeedbackRequestToJSONTyped(value?: ConsiderInsightsFromFeedbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rawFeedback': value['rawFeedback'],
        'source': value['source'],
    };
}

