/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerSolutionToBuild agent
 * @export
 * @interface ConsiderSolutionToBuildRequest
 */
export interface ConsiderSolutionToBuildRequest {
    /**
     * ID of the opportunity to consider solutions for
     * @type {string}
     * @memberof ConsiderSolutionToBuildRequest
     */
    opportunityId: string;
}

/**
 * Check if a given object implements the ConsiderSolutionToBuildRequest interface.
 */
export function instanceOfConsiderSolutionToBuildRequest(value: object): value is ConsiderSolutionToBuildRequest {
    if (!('opportunityId' in value) || value['opportunityId'] === undefined) return false;
    return true;
}

export function ConsiderSolutionToBuildRequestFromJSON(json: any): ConsiderSolutionToBuildRequest {
    return ConsiderSolutionToBuildRequestFromJSONTyped(json, false);
}

export function ConsiderSolutionToBuildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderSolutionToBuildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityId': json['opportunityId'],
    };
}

export function ConsiderSolutionToBuildRequestToJSON(json: any): ConsiderSolutionToBuildRequest {
    return ConsiderSolutionToBuildRequestToJSONTyped(json, false);
}

export function ConsiderSolutionToBuildRequestToJSONTyped(value?: ConsiderSolutionToBuildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityId': value['opportunityId'],
    };
}

