/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerMergingOpportunities agent
 * @export
 * @interface ConsiderMergingOpportunitiesRequest
 */
export interface ConsiderMergingOpportunitiesRequest {
    /**
     * List of opportunity IDs to consider merging
     * @type {Array<string>}
     * @memberof ConsiderMergingOpportunitiesRequest
     */
    opportunityIds: Array<string>;
}

/**
 * Check if a given object implements the ConsiderMergingOpportunitiesRequest interface.
 */
export function instanceOfConsiderMergingOpportunitiesRequest(value: object): value is ConsiderMergingOpportunitiesRequest {
    if (!('opportunityIds' in value) || value['opportunityIds'] === undefined) return false;
    return true;
}

export function ConsiderMergingOpportunitiesRequestFromJSON(json: any): ConsiderMergingOpportunitiesRequest {
    return ConsiderMergingOpportunitiesRequestFromJSONTyped(json, false);
}

export function ConsiderMergingOpportunitiesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderMergingOpportunitiesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityIds': json['opportunityIds'],
    };
}

export function ConsiderMergingOpportunitiesRequestToJSON(json: any): ConsiderMergingOpportunitiesRequest {
    return ConsiderMergingOpportunitiesRequestToJSONTyped(json, false);
}

export function ConsiderMergingOpportunitiesRequestToJSONTyped(value?: ConsiderMergingOpportunitiesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityIds': value['opportunityIds'],
    };
}

