/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for considerPRDForSolution agent
 * @export
 * @interface ConsiderPRDForSolutionRequest
 */
export interface ConsiderPRDForSolutionRequest {
    /**
     * ID of the solution to generate PRD for
     * @type {string}
     * @memberof ConsiderPRDForSolutionRequest
     */
    solutionId: string;
    /**
     * ID of the opportunity this solution addresses
     * @type {string}
     * @memberof ConsiderPRDForSolutionRequest
     */
    opportunityId: string;
}

/**
 * Check if a given object implements the ConsiderPRDForSolutionRequest interface.
 */
export function instanceOfConsiderPRDForSolutionRequest(value: object): value is ConsiderPRDForSolutionRequest {
    if (!('solutionId' in value) || value['solutionId'] === undefined) return false;
    if (!('opportunityId' in value) || value['opportunityId'] === undefined) return false;
    return true;
}

export function ConsiderPRDForSolutionRequestFromJSON(json: any): ConsiderPRDForSolutionRequest {
    return ConsiderPRDForSolutionRequestFromJSONTyped(json, false);
}

export function ConsiderPRDForSolutionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderPRDForSolutionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'solutionId': json['solutionId'],
        'opportunityId': json['opportunityId'],
    };
}

export function ConsiderPRDForSolutionRequestToJSON(json: any): ConsiderPRDForSolutionRequest {
    return ConsiderPRDForSolutionRequestToJSONTyped(json, false);
}

export function ConsiderPRDForSolutionRequestToJSONTyped(value?: ConsiderPRDForSolutionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'solutionId': value['solutionId'],
        'opportunityId': value['opportunityId'],
    };
}

