/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateMetricPayloadId
 */
export interface CreateMetricPayloadId {
}

/**
 * Check if a given object implements the CreateMetricPayloadId interface.
 */
export function instanceOfCreateMetricPayloadId(value: object): value is CreateMetricPayloadId {
    return true;
}

export function CreateMetricPayloadIdFromJSON(json: any): CreateMetricPayloadId {
    return CreateMetricPayloadIdFromJSONTyped(json, false);
}

export function CreateMetricPayloadIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMetricPayloadId {
    return json;
}

export function CreateMetricPayloadIdToJSON(json: any): CreateMetricPayloadId {
    return CreateMetricPayloadIdToJSONTyped(json, false);
}

export function CreateMetricPayloadIdToJSONTyped(value?: CreateMetricPayloadId | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

