/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for creating knowledge
 * @export
 * @interface CreateKnowledgePayload
 */
export interface CreateKnowledgePayload {
    /**
     * An optional Knowledge ID must be a uuid
     * @type {string}
     * @memberof CreateKnowledgePayload
     */
    id?: string;
    /**
     * Knowledge title
     * @type {string}
     * @memberof CreateKnowledgePayload
     */
    title: string;
    /**
     * Knowledge description - a short summary of the knowledge
     * @type {string}
     * @memberof CreateKnowledgePayload
     */
    description: string;
    /**
     * Knowledge content - the full content of the knowledge
     * @type {string}
     * @memberof CreateKnowledgePayload
     */
    content: string;
}

/**
 * Check if a given object implements the CreateKnowledgePayload interface.
 */
export function instanceOfCreateKnowledgePayload(value: object): value is CreateKnowledgePayload {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateKnowledgePayloadFromJSON(json: any): CreateKnowledgePayload {
    return CreateKnowledgePayloadFromJSONTyped(json, false);
}

export function CreateKnowledgePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKnowledgePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'],
        'content': json['content'],
    };
}

export function CreateKnowledgePayloadToJSON(json: any): CreateKnowledgePayload {
    return CreateKnowledgePayloadToJSONTyped(json, false);
}

export function CreateKnowledgePayloadToJSONTyped(value?: CreateKnowledgePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'content': value['content'],
    };
}

