/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateOpportunity429ResponseError } from './CreateOpportunity429ResponseError.js';
import {
    CreateOpportunity429ResponseErrorFromJSON,
    CreateOpportunity429ResponseErrorFromJSONTyped,
    CreateOpportunity429ResponseErrorToJSON,
    CreateOpportunity429ResponseErrorToJSONTyped,
} from './CreateOpportunity429ResponseError.js';

/**
 * Too Many Requests - Rate limit exceeded
 * @export
 * @interface CreateOpportunity429Response
 */
export interface CreateOpportunity429Response {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateOpportunity429ResponseError}
     * @memberof CreateOpportunity429Response
     */
    error: CreateOpportunity429ResponseError;
}

/**
 * Check if a given object implements the CreateOpportunity429Response interface.
 */
export function instanceOfCreateOpportunity429Response(value: object): value is CreateOpportunity429Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function CreateOpportunity429ResponseFromJSON(json: any): CreateOpportunity429Response {
    return CreateOpportunity429ResponseFromJSONTyped(json, false);
}

export function CreateOpportunity429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOpportunity429Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': CreateOpportunity429ResponseErrorFromJSON(json['error']),
    };
}

export function CreateOpportunity429ResponseToJSON(json: any): CreateOpportunity429Response {
    return CreateOpportunity429ResponseToJSONTyped(json, false);
}

export function CreateOpportunity429ResponseToJSONTyped(value?: CreateOpportunity429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': CreateOpportunity429ResponseErrorToJSON(value['error']),
    };
}

