/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Feedback document upload request
 * @export
 * @interface CreateFeedbackDocumentPayload
 */
export interface CreateFeedbackDocumentPayload {
    /**
     * Name of the document to upload
     * @type {string}
     * @memberof CreateFeedbackDocumentPayload
     */
    fileName: string;
    /**
     * Source of the document
     * @type {string}
     * @memberof CreateFeedbackDocumentPayload
     */
    source?: string;
}

/**
 * Check if a given object implements the CreateFeedbackDocumentPayload interface.
 */
export function instanceOfCreateFeedbackDocumentPayload(value: object): value is CreateFeedbackDocumentPayload {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function CreateFeedbackDocumentPayloadFromJSON(json: any): CreateFeedbackDocumentPayload {
    return CreateFeedbackDocumentPayloadFromJSONTyped(json, false);
}

export function CreateFeedbackDocumentPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedbackDocumentPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function CreateFeedbackDocumentPayloadToJSON(json: any): CreateFeedbackDocumentPayload {
    return CreateFeedbackDocumentPayloadToJSONTyped(json, false);
}

export function CreateFeedbackDocumentPayloadToJSONTyped(value?: CreateFeedbackDocumentPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'source': value['source'],
    };
}

