/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SingleKnowledgeResponseWithUploadPdf } from './SingleKnowledgeResponseWithUploadPdf.js';
import {
    SingleKnowledgeResponseWithUploadPdfFromJSON,
    SingleKnowledgeResponseWithUploadPdfFromJSONTyped,
    SingleKnowledgeResponseWithUploadPdfToJSON,
    SingleKnowledgeResponseWithUploadPdfToJSONTyped,
} from './SingleKnowledgeResponseWithUploadPdf.js';

/**
 * 
 * @export
 * @interface CreateKnowledgeFromPdf200Response
 */
export interface CreateKnowledgeFromPdf200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {SingleKnowledgeResponseWithUploadPdf}
     * @memberof CreateKnowledgeFromPdf200Response
     */
    data: SingleKnowledgeResponseWithUploadPdf;
}

/**
 * Check if a given object implements the CreateKnowledgeFromPdf200Response interface.
 */
export function instanceOfCreateKnowledgeFromPdf200Response(value: object): value is CreateKnowledgeFromPdf200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateKnowledgeFromPdf200ResponseFromJSON(json: any): CreateKnowledgeFromPdf200Response {
    return CreateKnowledgeFromPdf200ResponseFromJSONTyped(json, false);
}

export function CreateKnowledgeFromPdf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKnowledgeFromPdf200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': SingleKnowledgeResponseWithUploadPdfFromJSON(json['data']),
    };
}

export function CreateKnowledgeFromPdf200ResponseToJSON(json: any): CreateKnowledgeFromPdf200Response {
    return CreateKnowledgeFromPdf200ResponseToJSONTyped(json, false);
}

export function CreateKnowledgeFromPdf200ResponseToJSONTyped(value?: CreateKnowledgeFromPdf200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': SingleKnowledgeResponseWithUploadPdfToJSON(value['data']),
    };
}

