/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for creating knowledge from a PDF file
 * @export
 * @interface CreateKnowledgeFromPdfPayload
 */
export interface CreateKnowledgeFromPdfPayload {
    /**
     * An optional Knowledge ID must be a uuid
     * @type {string}
     * @memberof CreateKnowledgeFromPdfPayload
     */
    id?: string;
    /**
     * The name of the file to create knowledge from
     * @type {string}
     * @memberof CreateKnowledgeFromPdfPayload
     */
    fileName: string;
}

/**
 * Check if a given object implements the CreateKnowledgeFromPdfPayload interface.
 */
export function instanceOfCreateKnowledgeFromPdfPayload(value: object): value is CreateKnowledgeFromPdfPayload {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function CreateKnowledgeFromPdfPayloadFromJSON(json: any): CreateKnowledgeFromPdfPayload {
    return CreateKnowledgeFromPdfPayloadFromJSONTyped(json, false);
}

export function CreateKnowledgeFromPdfPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKnowledgeFromPdfPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['fileName'],
    };
}

export function CreateKnowledgeFromPdfPayloadToJSON(json: any): CreateKnowledgeFromPdfPayload {
    return CreateKnowledgeFromPdfPayloadToJSONTyped(json, false);
}

export function CreateKnowledgeFromPdfPayloadToJSONTyped(value?: CreateKnowledgeFromPdfPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
    };
}

