/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateSolutionPayloadRefinementLogInner
 */
export interface CreateSolutionPayloadRefinementLogInner {
    /**
     * 
     * @type {string}
     * @memberof CreateSolutionPayloadRefinementLogInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSolutionPayloadRefinementLogInner
     */
    role: CreateSolutionPayloadRefinementLogInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateSolutionPayloadRefinementLogInner
     */
    content: string;
}


/**
 * @export
 */
export const CreateSolutionPayloadRefinementLogInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type CreateSolutionPayloadRefinementLogInnerRoleEnum = typeof CreateSolutionPayloadRefinementLogInnerRoleEnum[keyof typeof CreateSolutionPayloadRefinementLogInnerRoleEnum];


/**
 * Check if a given object implements the CreateSolutionPayloadRefinementLogInner interface.
 */
export function instanceOfCreateSolutionPayloadRefinementLogInner(value: object): value is CreateSolutionPayloadRefinementLogInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateSolutionPayloadRefinementLogInnerFromJSON(json: any): CreateSolutionPayloadRefinementLogInner {
    return CreateSolutionPayloadRefinementLogInnerFromJSONTyped(json, false);
}

export function CreateSolutionPayloadRefinementLogInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolutionPayloadRefinementLogInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'content': json['content'],
    };
}

export function CreateSolutionPayloadRefinementLogInnerToJSON(json: any): CreateSolutionPayloadRefinementLogInner {
    return CreateSolutionPayloadRefinementLogInnerToJSONTyped(json, false);
}

export function CreateSolutionPayloadRefinementLogInnerToJSONTyped(value?: CreateSolutionPayloadRefinementLogInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
    };
}

