/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateTopic200ResponseData } from './CreateTopic200ResponseData.js';
import {
    CreateTopic200ResponseDataFromJSON,
    CreateTopic200ResponseDataFromJSONTyped,
    CreateTopic200ResponseDataToJSON,
    CreateTopic200ResponseDataToJSONTyped,
} from './CreateTopic200ResponseData.js';

/**
 * Response containing a single topic
 * @export
 * @interface CreateTopic200Response
 */
export interface CreateTopic200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateTopic200ResponseData}
     * @memberof CreateTopic200Response
     */
    data: CreateTopic200ResponseData;
}

/**
 * Check if a given object implements the CreateTopic200Response interface.
 */
export function instanceOfCreateTopic200Response(value: object): value is CreateTopic200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateTopic200ResponseFromJSON(json: any): CreateTopic200Response {
    return CreateTopic200ResponseFromJSONTyped(json, false);
}

export function CreateTopic200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTopic200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': CreateTopic200ResponseDataFromJSON(json['data']),
    };
}

export function CreateTopic200ResponseToJSON(json: any): CreateTopic200Response {
    return CreateTopic200ResponseToJSONTyped(json, false);
}

export function CreateTopic200ResponseToJSONTyped(value?: CreateTopic200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': CreateTopic200ResponseDataToJSON(value['data']),
    };
}

