/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for creating an opportunity
 * @export
 * @interface CreateOpportunityPayload
 */
export interface CreateOpportunityPayload {
    /**
     * 
     * @type {string}
     * @memberof CreateOpportunityPayload
     */
    id?: string;
    /**
     * Title of the opportunity
     * @type {string}
     * @memberof CreateOpportunityPayload
     */
    title: string;
    /**
     * Description of the opportunity
     * @type {string}
     * @memberof CreateOpportunityPayload
     */
    description: string;
    /**
     * How the opportunity was created
     * @type {string}
     * @memberof CreateOpportunityPayload
     */
    createdBy: CreateOpportunityPayloadCreatedByEnum;
    /**
     * ID of the opportunity owner
     * @type {string}
     * @memberof CreateOpportunityPayload
     */
    ownerId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOpportunityPayload
     */
    solutionIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOpportunityPayload
     */
    insightIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOpportunityPayload
     */
    outcomeIds?: Array<string>;
}


/**
 * @export
 */
export const CreateOpportunityPayloadCreatedByEnum = {
    User: 'user',
    Generated: 'generated'
} as const;
export type CreateOpportunityPayloadCreatedByEnum = typeof CreateOpportunityPayloadCreatedByEnum[keyof typeof CreateOpportunityPayloadCreatedByEnum];


/**
 * Check if a given object implements the CreateOpportunityPayload interface.
 */
export function instanceOfCreateOpportunityPayload(value: object): value is CreateOpportunityPayload {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function CreateOpportunityPayloadFromJSON(json: any): CreateOpportunityPayload {
    return CreateOpportunityPayloadFromJSONTyped(json, false);
}

export function CreateOpportunityPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOpportunityPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'],
        'createdBy': json['createdBy'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'solutionIds': json['solutionIds'] == null ? undefined : json['solutionIds'],
        'insightIds': json['insightIds'] == null ? undefined : json['insightIds'],
        'outcomeIds': json['outcomeIds'] == null ? undefined : json['outcomeIds'],
    };
}

export function CreateOpportunityPayloadToJSON(json: any): CreateOpportunityPayload {
    return CreateOpportunityPayloadToJSONTyped(json, false);
}

export function CreateOpportunityPayloadToJSONTyped(value?: CreateOpportunityPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdBy': value['createdBy'],
        'ownerId': value['ownerId'],
        'solutionIds': value['solutionIds'],
        'insightIds': value['insightIds'],
        'outcomeIds': value['outcomeIds'],
    };
}

