/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolutionWithRelationships } from './SolutionWithRelationships.js';
import {
    SolutionWithRelationshipsFromJSON,
    SolutionWithRelationshipsFromJSONTyped,
    SolutionWithRelationshipsToJSON,
    SolutionWithRelationshipsToJSONTyped,
} from './SolutionWithRelationships.js';

/**
 * Response containing a single solution
 * @export
 * @interface CreateSolution200Response
 */
export interface CreateSolution200Response {
    [key: string]: any | any;
    /**
     * Solution data
     * @type {SolutionWithRelationships}
     * @memberof CreateSolution200Response
     */
    data: SolutionWithRelationships;
}

/**
 * Check if a given object implements the CreateSolution200Response interface.
 */
export function instanceOfCreateSolution200Response(value: object): value is CreateSolution200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateSolution200ResponseFromJSON(json: any): CreateSolution200Response {
    return CreateSolution200ResponseFromJSONTyped(json, false);
}

export function CreateSolution200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolution200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': SolutionWithRelationshipsFromJSON(json['data']),
    };
}

export function CreateSolution200ResponseToJSON(json: any): CreateSolution200Response {
    return CreateSolution200ResponseToJSONTyped(json, false);
}

export function CreateSolution200ResponseToJSONTyped(value?: CreateSolution200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': SolutionWithRelationshipsToJSON(value['data']),
    };
}

