/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FeedbackWithRelationships } from './FeedbackWithRelationships.js';
import {
    FeedbackWithRelationshipsFromJSON,
    FeedbackWithRelationshipsFromJSONTyped,
    FeedbackWithRelationshipsToJSON,
    FeedbackWithRelationshipsToJSONTyped,
} from './FeedbackWithRelationships.js';

/**
 * Response containing a single feedback item
 * @export
 * @interface CreateFeedback200Response
 */
export interface CreateFeedback200Response {
    [key: string]: any | any;
    /**
     * Feedback data
     * @type {FeedbackWithRelationships}
     * @memberof CreateFeedback200Response
     */
    data: FeedbackWithRelationships;
}

/**
 * Check if a given object implements the CreateFeedback200Response interface.
 */
export function instanceOfCreateFeedback200Response(value: object): value is CreateFeedback200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateFeedback200ResponseFromJSON(json: any): CreateFeedback200Response {
    return CreateFeedback200ResponseFromJSONTyped(json, false);
}

export function CreateFeedback200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedback200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': FeedbackWithRelationshipsFromJSON(json['data']),
    };
}

export function CreateFeedback200ResponseToJSON(json: any): CreateFeedback200Response {
    return CreateFeedback200ResponseToJSONTyped(json, false);
}

export function CreateFeedback200ResponseToJSONTyped(value?: CreateFeedback200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': FeedbackWithRelationshipsToJSON(value['data']),
    };
}

