/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for creating knowledge from a URL
 * @export
 * @interface CreateKnowledgeFromUrlPayload
 */
export interface CreateKnowledgeFromUrlPayload {
    /**
     * An optional Knowledge ID must be a uuid
     * @type {string}
     * @memberof CreateKnowledgeFromUrlPayload
     */
    id?: string;
    /**
     * The URL the user wishes to create knowledge from
     * @type {string}
     * @memberof CreateKnowledgeFromUrlPayload
     */
    url: string;
}

/**
 * Check if a given object implements the CreateKnowledgeFromUrlPayload interface.
 */
export function instanceOfCreateKnowledgeFromUrlPayload(value: object): value is CreateKnowledgeFromUrlPayload {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateKnowledgeFromUrlPayloadFromJSON(json: any): CreateKnowledgeFromUrlPayload {
    return CreateKnowledgeFromUrlPayloadFromJSONTyped(json, false);
}

export function CreateKnowledgeFromUrlPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKnowledgeFromUrlPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'],
    };
}

export function CreateKnowledgeFromUrlPayloadToJSON(json: any): CreateKnowledgeFromUrlPayload {
    return CreateKnowledgeFromUrlPayloadToJSONTyped(json, false);
}

export function CreateKnowledgeFromUrlPayloadToJSONTyped(value?: CreateKnowledgeFromUrlPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

