/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for creating an integration
 * @export
 * @interface CreateIntegrationPayload
 */
export interface CreateIntegrationPayload {
    /**
     * 
     * @type {string}
     * @memberof CreateIntegrationPayload
     */
    integrationId: string;
    /**
     * 
     * @type {object}
     * @memberof CreateIntegrationPayload
     */
    config: object;
}

/**
 * Check if a given object implements the CreateIntegrationPayload interface.
 */
export function instanceOfCreateIntegrationPayload(value: object): value is CreateIntegrationPayload {
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function CreateIntegrationPayloadFromJSON(json: any): CreateIntegrationPayload {
    return CreateIntegrationPayloadFromJSONTyped(json, false);
}

export function CreateIntegrationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIntegrationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'integrationId': json['integrationId'],
        'config': json['config'],
    };
}

export function CreateIntegrationPayloadToJSON(json: any): CreateIntegrationPayload {
    return CreateIntegrationPayloadToJSONTyped(json, false);
}

export function CreateIntegrationPayloadToJSONTyped(value?: CreateIntegrationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'integrationId': value['integrationId'],
        'config': value['config'],
    };
}

