/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeleteOpportunity200ResponseData } from './DeleteOpportunity200ResponseData.js';
import {
    DeleteOpportunity200ResponseDataFromJSON,
    DeleteOpportunity200ResponseDataFromJSONTyped,
    DeleteOpportunity200ResponseDataToJSON,
    DeleteOpportunity200ResponseDataToJSONTyped,
} from './DeleteOpportunity200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface DeleteOpportunity200Response
 */
export interface DeleteOpportunity200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {DeleteOpportunity200ResponseData}
     * @memberof DeleteOpportunity200Response
     */
    data: DeleteOpportunity200ResponseData;
}

/**
 * Check if a given object implements the DeleteOpportunity200Response interface.
 */
export function instanceOfDeleteOpportunity200Response(value: object): value is DeleteOpportunity200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteOpportunity200ResponseFromJSON(json: any): DeleteOpportunity200Response {
    return DeleteOpportunity200ResponseFromJSONTyped(json, false);
}

export function DeleteOpportunity200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOpportunity200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': DeleteOpportunity200ResponseDataFromJSON(json['data']),
    };
}

export function DeleteOpportunity200ResponseToJSON(json: any): DeleteOpportunity200Response {
    return DeleteOpportunity200ResponseToJSONTyped(json, false);
}

export function DeleteOpportunity200ResponseToJSONTyped(value?: DeleteOpportunity200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': DeleteOpportunity200ResponseDataToJSON(value['data']),
    };
}

