/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Success message data
 * @export
 * @interface DeleteMetric200ResponseData
 */
export interface DeleteMetric200ResponseData {
    [key: string]: any | any;
    /**
     * Success flag
     * @type {boolean}
     * @memberof DeleteMetric200ResponseData
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteMetric200ResponseData interface.
 */
export function instanceOfDeleteMetric200ResponseData(value: object): value is DeleteMetric200ResponseData {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteMetric200ResponseDataFromJSON(json: any): DeleteMetric200ResponseData {
    return DeleteMetric200ResponseDataFromJSONTyped(json, false);
}

export function DeleteMetric200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMetric200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
    };
}

export function DeleteMetric200ResponseDataToJSON(json: any): DeleteMetric200ResponseData {
    return DeleteMetric200ResponseDataToJSONTyped(json, false);
}

export function DeleteMetric200ResponseDataToJSONTyped(value?: DeleteMetric200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
    };
}

