/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeleteSolution200ResponseData } from './DeleteSolution200ResponseData.js';
import {
    DeleteSolution200ResponseDataFromJSON,
    DeleteSolution200ResponseDataFromJSONTyped,
    DeleteSolution200ResponseDataToJSON,
    DeleteSolution200ResponseDataToJSONTyped,
} from './DeleteSolution200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface DeleteSolution200Response
 */
export interface DeleteSolution200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {DeleteSolution200ResponseData}
     * @memberof DeleteSolution200Response
     */
    data: DeleteSolution200ResponseData;
}

/**
 * Check if a given object implements the DeleteSolution200Response interface.
 */
export function instanceOfDeleteSolution200Response(value: object): value is DeleteSolution200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteSolution200ResponseFromJSON(json: any): DeleteSolution200Response {
    return DeleteSolution200ResponseFromJSONTyped(json, false);
}

export function DeleteSolution200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSolution200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': DeleteSolution200ResponseDataFromJSON(json['data']),
    };
}

export function DeleteSolution200ResponseToJSON(json: any): DeleteSolution200Response {
    return DeleteSolution200ResponseToJSONTyped(json, false);
}

export function DeleteSolution200ResponseToJSONTyped(value?: DeleteSolution200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': DeleteSolution200ResponseDataToJSON(value['data']),
    };
}

