/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Success message data
 * @export
 * @interface DeleteOpportunity200ResponseData
 */
export interface DeleteOpportunity200ResponseData {
    [key: string]: any | any;
    /**
     * Success message
     * @type {string}
     * @memberof DeleteOpportunity200ResponseData
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteOpportunity200ResponseData interface.
 */
export function instanceOfDeleteOpportunity200ResponseData(value: object): value is DeleteOpportunity200ResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteOpportunity200ResponseDataFromJSON(json: any): DeleteOpportunity200ResponseData {
    return DeleteOpportunity200ResponseDataFromJSONTyped(json, false);
}

export function DeleteOpportunity200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOpportunity200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'message': json['message'],
    };
}

export function DeleteOpportunity200ResponseDataToJSON(json: any): DeleteOpportunity200ResponseData {
    return DeleteOpportunity200ResponseDataToJSONTyped(json, false);
}

export function DeleteOpportunity200ResponseDataToJSONTyped(value?: DeleteOpportunity200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'message': value['message'],
    };
}

