/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Success message data
 * @export
 * @interface DeleteInsight200ResponseData
 */
export interface DeleteInsight200ResponseData {
    [key: string]: any | any;
    /**
     * Success message
     * @type {string}
     * @memberof DeleteInsight200ResponseData
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteInsight200ResponseData interface.
 */
export function instanceOfDeleteInsight200ResponseData(value: object): value is DeleteInsight200ResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteInsight200ResponseDataFromJSON(json: any): DeleteInsight200ResponseData {
    return DeleteInsight200ResponseDataFromJSONTyped(json, false);
}

export function DeleteInsight200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteInsight200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'message': json['message'],
    };
}

export function DeleteInsight200ResponseDataToJSON(json: any): DeleteInsight200ResponseData {
    return DeleteInsight200ResponseDataToJSONTyped(json, false);
}

export function DeleteInsight200ResponseDataToJSONTyped(value?: DeleteInsight200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'message': value['message'],
    };
}

