/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeleteMetric200ResponseData } from './DeleteMetric200ResponseData.js';
import {
    DeleteMetric200ResponseDataFromJSON,
    DeleteMetric200ResponseDataFromJSONTyped,
    DeleteMetric200ResponseDataToJSON,
    DeleteMetric200ResponseDataToJSONTyped,
} from './DeleteMetric200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface DeleteMetric200Response
 */
export interface DeleteMetric200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {DeleteMetric200ResponseData}
     * @memberof DeleteMetric200Response
     */
    data: DeleteMetric200ResponseData;
}

/**
 * Check if a given object implements the DeleteMetric200Response interface.
 */
export function instanceOfDeleteMetric200Response(value: object): value is DeleteMetric200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteMetric200ResponseFromJSON(json: any): DeleteMetric200Response {
    return DeleteMetric200ResponseFromJSONTyped(json, false);
}

export function DeleteMetric200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMetric200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': DeleteMetric200ResponseDataFromJSON(json['data']),
    };
}

export function DeleteMetric200ResponseToJSON(json: any): DeleteMetric200Response {
    return DeleteMetric200ResponseToJSONTyped(json, false);
}

export function DeleteMetric200ResponseToJSONTyped(value?: DeleteMetric200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': DeleteMetric200ResponseDataToJSON(value['data']),
    };
}

