/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetOrganisation404ResponseError
 */
export interface GetOrganisation404ResponseError {
    [key: string]: any | any;
    /**
     * Error code identifier
     * @type {string}
     * @memberof GetOrganisation404ResponseError
     */
    code: string;
    /**
     * Human-readable error description
     * @type {string}
     * @memberof GetOrganisation404ResponseError
     */
    description: string;
}

/**
 * Check if a given object implements the GetOrganisation404ResponseError interface.
 */
export function instanceOfGetOrganisation404ResponseError(value: object): value is GetOrganisation404ResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetOrganisation404ResponseErrorFromJSON(json: any): GetOrganisation404ResponseError {
    return GetOrganisation404ResponseErrorFromJSONTyped(json, false);
}

export function GetOrganisation404ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganisation404ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'description': json['description'],
    };
}

export function GetOrganisation404ResponseErrorToJSON(json: any): GetOrganisation404ResponseError {
    return GetOrganisation404ResponseErrorToJSONTyped(json, false);
}

export function GetOrganisation404ResponseErrorToJSONTyped(value?: GetOrganisation404ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'description': value['description'],
    };
}

