/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetOrganisation404ResponseError } from './GetOrganisation404ResponseError.js';
import {
    GetOrganisation404ResponseErrorFromJSON,
    GetOrganisation404ResponseErrorFromJSONTyped,
    GetOrganisation404ResponseErrorToJSON,
    GetOrganisation404ResponseErrorToJSONTyped,
} from './GetOrganisation404ResponseError.js';

/**
 * Not Found - The requested resource does not exist
 * @export
 * @interface GetOrganisation404Response
 */
export interface GetOrganisation404Response {
    [key: string]: any | any;
    /**
     * 
     * @type {GetOrganisation404ResponseError}
     * @memberof GetOrganisation404Response
     */
    error: GetOrganisation404ResponseError;
}

/**
 * Check if a given object implements the GetOrganisation404Response interface.
 */
export function instanceOfGetOrganisation404Response(value: object): value is GetOrganisation404Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetOrganisation404ResponseFromJSON(json: any): GetOrganisation404Response {
    return GetOrganisation404ResponseFromJSONTyped(json, false);
}

export function GetOrganisation404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganisation404Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': GetOrganisation404ResponseErrorFromJSON(json['error']),
    };
}

export function GetOrganisation404ResponseToJSON(json: any): GetOrganisation404Response {
    return GetOrganisation404ResponseToJSONTyped(json, false);
}

export function GetOrganisation404ResponseToJSONTyped(value?: GetOrganisation404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': GetOrganisation404ResponseErrorToJSON(value['error']),
    };
}

