/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Google Reviews integration configuration in API response (sanitized)
 * @export
 * @interface GoogleReviewsResponseConfig
 */
export interface GoogleReviewsResponseConfig {
    /**
     * Whether the Google Reviews integration is active
     * @type {boolean}
     * @memberof GoogleReviewsResponseConfig
     */
    active: boolean;
    /**
     * Name of the business
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    businessName: string;
    /**
     * Google Maps place ID
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    placeId: string;
    /**
     * User ID who created this integration
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    createdBy: string;
    /**
     * Total number of reviews read so far
     * @type {number}
     * @memberof GoogleReviewsResponseConfig
     */
    totalReviewsRead: number;
    /**
     * ID of the last review that was read
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    lastReadReviewsId: string | null;
    /**
     * Number of reviews in the last sync
     * @type {number}
     * @memberof GoogleReviewsResponseConfig
     */
    lastReviewCount: number;
    /**
     * Unix timestamp of the last review read
     * @type {number}
     * @memberof GoogleReviewsResponseConfig
     */
    lastReadReviewsDate: number | null;
    /**
     * Unix timestamp of the last sync run
     * @type {number}
     * @memberof GoogleReviewsResponseConfig
     */
    lastRunDate: number | null;
    /**
     * ISO 3166-1 alpha-2 country code (lowercase)
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    country: string;
    /**
     * DataForSEO location code (derived from country)
     * @type {number}
     * @memberof GoogleReviewsResponseConfig
     */
    locationCode: number;
    /**
     * ISO 639-1 language code (lowercase)
     * @type {string}
     * @memberof GoogleReviewsResponseConfig
     */
    languageCode: string;
}

/**
 * Check if a given object implements the GoogleReviewsResponseConfig interface.
 */
export function instanceOfGoogleReviewsResponseConfig(value: object): value is GoogleReviewsResponseConfig {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('businessName' in value) || value['businessName'] === undefined) return false;
    if (!('placeId' in value) || value['placeId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('totalReviewsRead' in value) || value['totalReviewsRead'] === undefined) return false;
    if (!('lastReadReviewsId' in value) || value['lastReadReviewsId'] === undefined) return false;
    if (!('lastReviewCount' in value) || value['lastReviewCount'] === undefined) return false;
    if (!('lastReadReviewsDate' in value) || value['lastReadReviewsDate'] === undefined) return false;
    if (!('lastRunDate' in value) || value['lastRunDate'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('locationCode' in value) || value['locationCode'] === undefined) return false;
    if (!('languageCode' in value) || value['languageCode'] === undefined) return false;
    return true;
}

export function GoogleReviewsResponseConfigFromJSON(json: any): GoogleReviewsResponseConfig {
    return GoogleReviewsResponseConfigFromJSONTyped(json, false);
}

export function GoogleReviewsResponseConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleReviewsResponseConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'businessName': json['business_name'],
        'placeId': json['place_id'],
        'createdBy': json['created_by'],
        'totalReviewsRead': json['total_reviews_read'],
        'lastReadReviewsId': json['last_read_reviews_id'],
        'lastReviewCount': json['last_review_count'],
        'lastReadReviewsDate': json['last_read_reviews_date'],
        'lastRunDate': json['last_run_date'],
        'country': json['country'],
        'locationCode': json['location_code'],
        'languageCode': json['language_code'],
    };
}

export function GoogleReviewsResponseConfigToJSON(json: any): GoogleReviewsResponseConfig {
    return GoogleReviewsResponseConfigToJSONTyped(json, false);
}

export function GoogleReviewsResponseConfigToJSONTyped(value?: GoogleReviewsResponseConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'business_name': value['businessName'],
        'place_id': value['placeId'],
        'created_by': value['createdBy'],
        'total_reviews_read': value['totalReviewsRead'],
        'last_read_reviews_id': value['lastReadReviewsId'],
        'last_review_count': value['lastReviewCount'],
        'last_read_reviews_date': value['lastReadReviewsDate'],
        'last_run_date': value['lastRunDate'],
        'country': value['country'],
        'location_code': value['locationCode'],
        'language_code': value['languageCode'],
    };
}

