/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AppStoreIntegration } from './AppStoreIntegration.js';
import {
    instanceOfAppStoreIntegration,
    AppStoreIntegrationFromJSON,
    AppStoreIntegrationFromJSONTyped,
    AppStoreIntegrationToJSON,
} from './AppStoreIntegration.js';
import type { GongIntegration } from './GongIntegration.js';
import {
    instanceOfGongIntegration,
    GongIntegrationFromJSON,
    GongIntegrationFromJSONTyped,
    GongIntegrationToJSON,
} from './GongIntegration.js';
import type { GoogleReviewsIntegration } from './GoogleReviewsIntegration.js';
import {
    instanceOfGoogleReviewsIntegration,
    GoogleReviewsIntegrationFromJSON,
    GoogleReviewsIntegrationFromJSONTyped,
    GoogleReviewsIntegrationToJSON,
} from './GoogleReviewsIntegration.js';
import type { NotionIntegration } from './NotionIntegration.js';
import {
    instanceOfNotionIntegration,
    NotionIntegrationFromJSON,
    NotionIntegrationFromJSONTyped,
    NotionIntegrationToJSON,
} from './NotionIntegration.js';
import type { PlayStoreIntegration } from './PlayStoreIntegration.js';
import {
    instanceOfPlayStoreIntegration,
    PlayStoreIntegrationFromJSON,
    PlayStoreIntegrationFromJSONTyped,
    PlayStoreIntegrationToJSON,
} from './PlayStoreIntegration.js';
import type { TrustpilotIntegration } from './TrustpilotIntegration.js';
import {
    instanceOfTrustpilotIntegration,
    TrustpilotIntegrationFromJSON,
    TrustpilotIntegrationFromJSONTyped,
    TrustpilotIntegrationToJSON,
} from './TrustpilotIntegration.js';
import type { TypeformIntegration } from './TypeformIntegration.js';
import {
    instanceOfTypeformIntegration,
    TypeformIntegrationFromJSON,
    TypeformIntegrationFromJSONTyped,
    TypeformIntegrationToJSON,
} from './TypeformIntegration.js';

/**
 * @type Integration
 * Integration record
 * @export
 */
export type Integration = { integrationId: 'APP_STORE_REVIEWS' } & AppStoreIntegration | { integrationId: 'GONG' } & GongIntegration | { integrationId: 'GOOGLE_REVIEWS' } & GoogleReviewsIntegration | { integrationId: 'NOTION' } & NotionIntegration | { integrationId: 'PLAY_STORE_REVIEWS' } & PlayStoreIntegration | { integrationId: 'TRUSTPILOT_REVIEWS' } & TrustpilotIntegration | { integrationId: 'TYPEFORM' } & TypeformIntegration;

export function IntegrationFromJSON(json: any): Integration {
    return IntegrationFromJSONTyped(json, false);
}

export function IntegrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Integration {
    if (json == null) {
        return json;
    }
    switch (json['integrationId']) {
        case 'APP_STORE_REVIEWS':
            return Object.assign({}, AppStoreIntegrationFromJSONTyped(json, true), { integrationId: 'APP_STORE_REVIEWS' } as const);
        case 'GONG':
            return Object.assign({}, GongIntegrationFromJSONTyped(json, true), { integrationId: 'GONG' } as const);
        case 'GOOGLE_REVIEWS':
            return Object.assign({}, GoogleReviewsIntegrationFromJSONTyped(json, true), { integrationId: 'GOOGLE_REVIEWS' } as const);
        case 'NOTION':
            return Object.assign({}, NotionIntegrationFromJSONTyped(json, true), { integrationId: 'NOTION' } as const);
        case 'PLAY_STORE_REVIEWS':
            return Object.assign({}, PlayStoreIntegrationFromJSONTyped(json, true), { integrationId: 'PLAY_STORE_REVIEWS' } as const);
        case 'TRUSTPILOT_REVIEWS':
            return Object.assign({}, TrustpilotIntegrationFromJSONTyped(json, true), { integrationId: 'TRUSTPILOT_REVIEWS' } as const);
        case 'TYPEFORM':
            return Object.assign({}, TypeformIntegrationFromJSONTyped(json, true), { integrationId: 'TYPEFORM' } as const);
        default:
            throw new Error(`No variant of Integration exists with 'integrationId=${json['integrationId']}'`);
    }
}

export function IntegrationToJSON(json: any): any {
    return IntegrationToJSONTyped(json, false);
}

export function IntegrationToJSONTyped(value?: Integration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['integrationId']) {
        case 'APP_STORE_REVIEWS':
            return Object.assign({}, AppStoreIntegrationToJSON(value), { integrationId: 'APP_STORE_REVIEWS' } as const);
        case 'GONG':
            return Object.assign({}, GongIntegrationToJSON(value), { integrationId: 'GONG' } as const);
        case 'GOOGLE_REVIEWS':
            return Object.assign({}, GoogleReviewsIntegrationToJSON(value), { integrationId: 'GOOGLE_REVIEWS' } as const);
        case 'NOTION':
            return Object.assign({}, NotionIntegrationToJSON(value), { integrationId: 'NOTION' } as const);
        case 'PLAY_STORE_REVIEWS':
            return Object.assign({}, PlayStoreIntegrationToJSON(value), { integrationId: 'PLAY_STORE_REVIEWS' } as const);
        case 'TRUSTPILOT_REVIEWS':
            return Object.assign({}, TrustpilotIntegrationToJSON(value), { integrationId: 'TRUSTPILOT_REVIEWS' } as const);
        case 'TYPEFORM':
            return Object.assign({}, TypeformIntegrationToJSON(value), { integrationId: 'TYPEFORM' } as const);
        default:
            throw new Error(`No variant of Integration exists with 'integrationId=${value['integrationId']}'`);
    }

}

