/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InvokeAgentRequestOneOf } from './InvokeAgentRequestOneOf.js';
import {
    instanceOfInvokeAgentRequestOneOf,
    InvokeAgentRequestOneOfFromJSON,
    InvokeAgentRequestOneOfFromJSONTyped,
    InvokeAgentRequestOneOfToJSON,
} from './InvokeAgentRequestOneOf.js';
import type { InvokeAgentRequestOneOf1 } from './InvokeAgentRequestOneOf1.js';
import {
    instanceOfInvokeAgentRequestOneOf1,
    InvokeAgentRequestOneOf1FromJSON,
    InvokeAgentRequestOneOf1FromJSONTyped,
    InvokeAgentRequestOneOf1ToJSON,
} from './InvokeAgentRequestOneOf1.js';
import type { InvokeAgentRequestOneOf2 } from './InvokeAgentRequestOneOf2.js';
import {
    instanceOfInvokeAgentRequestOneOf2,
    InvokeAgentRequestOneOf2FromJSON,
    InvokeAgentRequestOneOf2FromJSONTyped,
    InvokeAgentRequestOneOf2ToJSON,
} from './InvokeAgentRequestOneOf2.js';
import type { InvokeAgentRequestOneOf3 } from './InvokeAgentRequestOneOf3.js';
import {
    instanceOfInvokeAgentRequestOneOf3,
    InvokeAgentRequestOneOf3FromJSON,
    InvokeAgentRequestOneOf3FromJSONTyped,
    InvokeAgentRequestOneOf3ToJSON,
} from './InvokeAgentRequestOneOf3.js';
import type { InvokeAgentRequestOneOf4 } from './InvokeAgentRequestOneOf4.js';
import {
    instanceOfInvokeAgentRequestOneOf4,
    InvokeAgentRequestOneOf4FromJSON,
    InvokeAgentRequestOneOf4FromJSONTyped,
    InvokeAgentRequestOneOf4ToJSON,
} from './InvokeAgentRequestOneOf4.js';
import type { InvokeAgentRequestOneOf5 } from './InvokeAgentRequestOneOf5.js';
import {
    instanceOfInvokeAgentRequestOneOf5,
    InvokeAgentRequestOneOf5FromJSON,
    InvokeAgentRequestOneOf5FromJSONTyped,
    InvokeAgentRequestOneOf5ToJSON,
} from './InvokeAgentRequestOneOf5.js';
import type { InvokeAgentRequestOneOf6 } from './InvokeAgentRequestOneOf6.js';
import {
    instanceOfInvokeAgentRequestOneOf6,
    InvokeAgentRequestOneOf6FromJSON,
    InvokeAgentRequestOneOf6FromJSONTyped,
    InvokeAgentRequestOneOf6ToJSON,
} from './InvokeAgentRequestOneOf6.js';
import type { InvokeAgentRequestOneOf7 } from './InvokeAgentRequestOneOf7.js';
import {
    instanceOfInvokeAgentRequestOneOf7,
    InvokeAgentRequestOneOf7FromJSON,
    InvokeAgentRequestOneOf7FromJSONTyped,
    InvokeAgentRequestOneOf7ToJSON,
} from './InvokeAgentRequestOneOf7.js';
import type { InvokeAgentRequestOneOf8 } from './InvokeAgentRequestOneOf8.js';
import {
    instanceOfInvokeAgentRequestOneOf8,
    InvokeAgentRequestOneOf8FromJSON,
    InvokeAgentRequestOneOf8FromJSONTyped,
    InvokeAgentRequestOneOf8ToJSON,
} from './InvokeAgentRequestOneOf8.js';

/**
 * @type InvokeAgentRequest
 * 
 * @export
 */
export type InvokeAgentRequest = InvokeAgentRequestOneOf | InvokeAgentRequestOneOf1 | InvokeAgentRequestOneOf2 | InvokeAgentRequestOneOf3 | InvokeAgentRequestOneOf4 | InvokeAgentRequestOneOf5 | InvokeAgentRequestOneOf6 | InvokeAgentRequestOneOf7 | InvokeAgentRequestOneOf8;

export function InvokeAgentRequestFromJSON(json: any): InvokeAgentRequest {
    return InvokeAgentRequestFromJSONTyped(json, false);
}

export function InvokeAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentRequest {
    if (json == null) {
        return json;
    }
    if (instanceOfInvokeAgentRequestOneOf(json)) {
        return InvokeAgentRequestOneOfFromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf1(json)) {
        return InvokeAgentRequestOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf2(json)) {
        return InvokeAgentRequestOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf3(json)) {
        return InvokeAgentRequestOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf4(json)) {
        return InvokeAgentRequestOneOf4FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf5(json)) {
        return InvokeAgentRequestOneOf5FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf6(json)) {
        return InvokeAgentRequestOneOf6FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf7(json)) {
        return InvokeAgentRequestOneOf7FromJSONTyped(json, true);
    }
    if (instanceOfInvokeAgentRequestOneOf8(json)) {
        return InvokeAgentRequestOneOf8FromJSONTyped(json, true);
    }

    return {} as any;
}

export function InvokeAgentRequestToJSON(json: any): any {
    return InvokeAgentRequestToJSONTyped(json, false);
}

export function InvokeAgentRequestToJSONTyped(value?: InvokeAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfInvokeAgentRequestOneOf(value)) {
        return InvokeAgentRequestOneOfToJSON(value as InvokeAgentRequestOneOf);
    }
    if (instanceOfInvokeAgentRequestOneOf1(value)) {
        return InvokeAgentRequestOneOf1ToJSON(value as InvokeAgentRequestOneOf1);
    }
    if (instanceOfInvokeAgentRequestOneOf2(value)) {
        return InvokeAgentRequestOneOf2ToJSON(value as InvokeAgentRequestOneOf2);
    }
    if (instanceOfInvokeAgentRequestOneOf3(value)) {
        return InvokeAgentRequestOneOf3ToJSON(value as InvokeAgentRequestOneOf3);
    }
    if (instanceOfInvokeAgentRequestOneOf4(value)) {
        return InvokeAgentRequestOneOf4ToJSON(value as InvokeAgentRequestOneOf4);
    }
    if (instanceOfInvokeAgentRequestOneOf5(value)) {
        return InvokeAgentRequestOneOf5ToJSON(value as InvokeAgentRequestOneOf5);
    }
    if (instanceOfInvokeAgentRequestOneOf6(value)) {
        return InvokeAgentRequestOneOf6ToJSON(value as InvokeAgentRequestOneOf6);
    }
    if (instanceOfInvokeAgentRequestOneOf7(value)) {
        return InvokeAgentRequestOneOf7ToJSON(value as InvokeAgentRequestOneOf7);
    }
    if (instanceOfInvokeAgentRequestOneOf8(value)) {
        return InvokeAgentRequestOneOf8ToJSON(value as InvokeAgentRequestOneOf8);
    }

    return {};
}

