/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConsiderRecommendedSolutionsRequest } from './ConsiderRecommendedSolutionsRequest.js';
import {
    ConsiderRecommendedSolutionsRequestFromJSON,
    ConsiderRecommendedSolutionsRequestFromJSONTyped,
    ConsiderRecommendedSolutionsRequestToJSON,
    ConsiderRecommendedSolutionsRequestToJSONTyped,
} from './ConsiderRecommendedSolutionsRequest.js';

/**
 * 
 * @export
 * @interface InvokeAgentRequestOneOf1
 */
export interface InvokeAgentRequestOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof InvokeAgentRequestOneOf1
     */
    agent: InvokeAgentRequestOneOf1AgentEnum;
    /**
     * 
     * @type {ConsiderRecommendedSolutionsRequest}
     * @memberof InvokeAgentRequestOneOf1
     */
    data: ConsiderRecommendedSolutionsRequest;
}


/**
 * @export
 */
export const InvokeAgentRequestOneOf1AgentEnum = {
    ConsiderRecommendedSolutions: 'considerRecommendedSolutions'
} as const;
export type InvokeAgentRequestOneOf1AgentEnum = typeof InvokeAgentRequestOneOf1AgentEnum[keyof typeof InvokeAgentRequestOneOf1AgentEnum];


/**
 * Check if a given object implements the InvokeAgentRequestOneOf1 interface.
 */
export function instanceOfInvokeAgentRequestOneOf1(value: object): value is InvokeAgentRequestOneOf1 {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvokeAgentRequestOneOf1FromJSON(json: any): InvokeAgentRequestOneOf1 {
    return InvokeAgentRequestOneOf1FromJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentRequestOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'],
        'data': ConsiderRecommendedSolutionsRequestFromJSON(json['data']),
    };
}

export function InvokeAgentRequestOneOf1ToJSON(json: any): InvokeAgentRequestOneOf1 {
    return InvokeAgentRequestOneOf1ToJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf1ToJSONTyped(value?: InvokeAgentRequestOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': value['agent'],
        'data': ConsiderRecommendedSolutionsRequestToJSON(value['data']),
    };
}

