/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConsiderSolutionsToRoadmapRequest } from './ConsiderSolutionsToRoadmapRequest.js';
import {
    ConsiderSolutionsToRoadmapRequestFromJSON,
    ConsiderSolutionsToRoadmapRequestFromJSONTyped,
    ConsiderSolutionsToRoadmapRequestToJSON,
    ConsiderSolutionsToRoadmapRequestToJSONTyped,
} from './ConsiderSolutionsToRoadmapRequest.js';

/**
 * 
 * @export
 * @interface InvokeAgentRequestOneOf7
 */
export interface InvokeAgentRequestOneOf7 {
    /**
     * 
     * @type {string}
     * @memberof InvokeAgentRequestOneOf7
     */
    agent: InvokeAgentRequestOneOf7AgentEnum;
    /**
     * 
     * @type {ConsiderSolutionsToRoadmapRequest}
     * @memberof InvokeAgentRequestOneOf7
     */
    data: ConsiderSolutionsToRoadmapRequest;
}


/**
 * @export
 */
export const InvokeAgentRequestOneOf7AgentEnum = {
    ConsiderSolutionsToRoadmap: 'considerSolutionsToRoadmap'
} as const;
export type InvokeAgentRequestOneOf7AgentEnum = typeof InvokeAgentRequestOneOf7AgentEnum[keyof typeof InvokeAgentRequestOneOf7AgentEnum];


/**
 * Check if a given object implements the InvokeAgentRequestOneOf7 interface.
 */
export function instanceOfInvokeAgentRequestOneOf7(value: object): value is InvokeAgentRequestOneOf7 {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvokeAgentRequestOneOf7FromJSON(json: any): InvokeAgentRequestOneOf7 {
    return InvokeAgentRequestOneOf7FromJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf7FromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentRequestOneOf7 {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'],
        'data': ConsiderSolutionsToRoadmapRequestFromJSON(json['data']),
    };
}

export function InvokeAgentRequestOneOf7ToJSON(json: any): InvokeAgentRequestOneOf7 {
    return InvokeAgentRequestOneOf7ToJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf7ToJSONTyped(value?: InvokeAgentRequestOneOf7 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': value['agent'],
        'data': ConsiderSolutionsToRoadmapRequestToJSON(value['data']),
    };
}

