/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MakeOpportunityFromInsightsRequest } from './MakeOpportunityFromInsightsRequest.js';
import {
    MakeOpportunityFromInsightsRequestFromJSON,
    MakeOpportunityFromInsightsRequestFromJSONTyped,
    MakeOpportunityFromInsightsRequestToJSON,
    MakeOpportunityFromInsightsRequestToJSONTyped,
} from './MakeOpportunityFromInsightsRequest.js';

/**
 * 
 * @export
 * @interface InvokeAgentRequestOneOf2
 */
export interface InvokeAgentRequestOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof InvokeAgentRequestOneOf2
     */
    agent: InvokeAgentRequestOneOf2AgentEnum;
    /**
     * 
     * @type {MakeOpportunityFromInsightsRequest}
     * @memberof InvokeAgentRequestOneOf2
     */
    data: MakeOpportunityFromInsightsRequest;
}


/**
 * @export
 */
export const InvokeAgentRequestOneOf2AgentEnum = {
    MakeOpportunityFromInsights: 'makeOpportunityFromInsights'
} as const;
export type InvokeAgentRequestOneOf2AgentEnum = typeof InvokeAgentRequestOneOf2AgentEnum[keyof typeof InvokeAgentRequestOneOf2AgentEnum];


/**
 * Check if a given object implements the InvokeAgentRequestOneOf2 interface.
 */
export function instanceOfInvokeAgentRequestOneOf2(value: object): value is InvokeAgentRequestOneOf2 {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvokeAgentRequestOneOf2FromJSON(json: any): InvokeAgentRequestOneOf2 {
    return InvokeAgentRequestOneOf2FromJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentRequestOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'],
        'data': MakeOpportunityFromInsightsRequestFromJSON(json['data']),
    };
}

export function InvokeAgentRequestOneOf2ToJSON(json: any): InvokeAgentRequestOneOf2 {
    return InvokeAgentRequestOneOf2ToJSONTyped(json, false);
}

export function InvokeAgentRequestOneOf2ToJSONTyped(value?: InvokeAgentRequestOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': value['agent'],
        'data': MakeOpportunityFromInsightsRequestToJSON(value['data']),
    };
}

