/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Knowledge } from './Knowledge.js';
import {
    KnowledgeFromJSON,
    KnowledgeFromJSONTyped,
    KnowledgeToJSON,
    KnowledgeToJSONTyped,
} from './Knowledge.js';

/**
 * Response containing an array of knowledge
 * @export
 * @interface KnowledgeArrayResponse
 */
export interface KnowledgeArrayResponse {
    /**
     * Array of knowledge
     * @type {Array<Knowledge>}
     * @memberof KnowledgeArrayResponse
     */
    data: Array<Knowledge>;
}

/**
 * Check if a given object implements the KnowledgeArrayResponse interface.
 */
export function instanceOfKnowledgeArrayResponse(value: object): value is KnowledgeArrayResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function KnowledgeArrayResponseFromJSON(json: any): KnowledgeArrayResponse {
    return KnowledgeArrayResponseFromJSONTyped(json, false);
}

export function KnowledgeArrayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeArrayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(KnowledgeFromJSON)),
    };
}

export function KnowledgeArrayResponseToJSON(json: any): KnowledgeArrayResponse {
    return KnowledgeArrayResponseToJSONTyped(json, false);
}

export function KnowledgeArrayResponseToJSONTyped(value?: KnowledgeArrayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(KnowledgeToJSON)),
    };
}

