/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListOrganisations401ResponseError
 */
export interface ListOrganisations401ResponseError {
    [key: string]: any | any;
    /**
     * Error code identifier
     * @type {string}
     * @memberof ListOrganisations401ResponseError
     */
    code: string;
    /**
     * Human-readable error description
     * @type {string}
     * @memberof ListOrganisations401ResponseError
     */
    description: string;
}

/**
 * Check if a given object implements the ListOrganisations401ResponseError interface.
 */
export function instanceOfListOrganisations401ResponseError(value: object): value is ListOrganisations401ResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ListOrganisations401ResponseErrorFromJSON(json: any): ListOrganisations401ResponseError {
    return ListOrganisations401ResponseErrorFromJSONTyped(json, false);
}

export function ListOrganisations401ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisations401ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'description': json['description'],
    };
}

export function ListOrganisations401ResponseErrorToJSON(json: any): ListOrganisations401ResponseError {
    return ListOrganisations401ResponseErrorToJSONTyped(json, false);
}

export function ListOrganisations401ResponseErrorToJSONTyped(value?: ListOrganisations401ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'description': value['description'],
    };
}

