/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolutionWithRelationships } from './SolutionWithRelationships.js';
import {
    SolutionWithRelationshipsFromJSON,
    SolutionWithRelationshipsFromJSONTyped,
    SolutionWithRelationshipsToJSON,
    SolutionWithRelationshipsToJSONTyped,
} from './SolutionWithRelationships.js';

/**
 * Response containing an array of solutions
 * @export
 * @interface ListSolutions200Response
 */
export interface ListSolutions200Response {
    [key: string]: any | any;
    /**
     * Array of solutions
     * @type {Array<SolutionWithRelationships>}
     * @memberof ListSolutions200Response
     */
    data: Array<SolutionWithRelationships>;
}

/**
 * Check if a given object implements the ListSolutions200Response interface.
 */
export function instanceOfListSolutions200Response(value: object): value is ListSolutions200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListSolutions200ResponseFromJSON(json: any): ListSolutions200Response {
    return ListSolutions200ResponseFromJSONTyped(json, false);
}

export function ListSolutions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSolutions200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': ((json['data'] as Array<any>).map(SolutionWithRelationshipsFromJSON)),
    };
}

export function ListSolutions200ResponseToJSON(json: any): ListSolutions200Response {
    return ListSolutions200ResponseToJSONTyped(json, false);
}

export function ListSolutions200ResponseToJSONTyped(value?: ListSolutions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': ((value['data'] as Array<any>).map(SolutionWithRelationshipsToJSON)),
    };
}

