/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListOrganisations401ResponseError } from './ListOrganisations401ResponseError.js';
import {
    ListOrganisations401ResponseErrorFromJSON,
    ListOrganisations401ResponseErrorFromJSONTyped,
    ListOrganisations401ResponseErrorToJSON,
    ListOrganisations401ResponseErrorToJSONTyped,
} from './ListOrganisations401ResponseError.js';

/**
 * Unauthorized - Missing or invalid authentication token
 * @export
 * @interface ListOrganisations401Response
 */
export interface ListOrganisations401Response {
    [key: string]: any | any;
    /**
     * 
     * @type {ListOrganisations401ResponseError}
     * @memberof ListOrganisations401Response
     */
    error: ListOrganisations401ResponseError;
}

/**
 * Check if a given object implements the ListOrganisations401Response interface.
 */
export function instanceOfListOrganisations401Response(value: object): value is ListOrganisations401Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListOrganisations401ResponseFromJSON(json: any): ListOrganisations401Response {
    return ListOrganisations401ResponseFromJSONTyped(json, false);
}

export function ListOrganisations401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisations401Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': ListOrganisations401ResponseErrorFromJSON(json['error']),
    };
}

export function ListOrganisations401ResponseToJSON(json: any): ListOrganisations401Response {
    return ListOrganisations401ResponseToJSONTyped(json, false);
}

export function ListOrganisations401ResponseToJSONTyped(value?: ListOrganisations401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': ListOrganisations401ResponseErrorToJSON(value['error']),
    };
}

