/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListOrganisations500ResponseError } from './ListOrganisations500ResponseError.js';
import {
    ListOrganisations500ResponseErrorFromJSON,
    ListOrganisations500ResponseErrorFromJSONTyped,
    ListOrganisations500ResponseErrorToJSON,
    ListOrganisations500ResponseErrorToJSONTyped,
} from './ListOrganisations500ResponseError.js';

/**
 * Internal Server Error - An unexpected error occurred on the server
 * @export
 * @interface ListOrganisations500Response
 */
export interface ListOrganisations500Response {
    [key: string]: any | any;
    /**
     * 
     * @type {ListOrganisations500ResponseError}
     * @memberof ListOrganisations500Response
     */
    error: ListOrganisations500ResponseError;
}

/**
 * Check if a given object implements the ListOrganisations500Response interface.
 */
export function instanceOfListOrganisations500Response(value: object): value is ListOrganisations500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListOrganisations500ResponseFromJSON(json: any): ListOrganisations500Response {
    return ListOrganisations500ResponseFromJSONTyped(json, false);
}

export function ListOrganisations500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisations500Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': ListOrganisations500ResponseErrorFromJSON(json['error']),
    };
}

export function ListOrganisations500ResponseToJSON(json: any): ListOrganisations500Response {
    return ListOrganisations500ResponseToJSONTyped(json, false);
}

export function ListOrganisations500ResponseToJSONTyped(value?: ListOrganisations500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': ListOrganisations500ResponseErrorToJSON(value['error']),
    };
}

