/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Workspace } from './Workspace.js';
import {
    WorkspaceFromJSON,
    WorkspaceFromJSONTyped,
    WorkspaceToJSON,
    WorkspaceToJSONTyped,
} from './Workspace.js';

/**
 * Response containing an array of workspaces
 * @export
 * @interface ListWorkspaces200Response
 */
export interface ListWorkspaces200Response {
    [key: string]: any | any;
    /**
     * Array of workspaces
     * @type {Array<Workspace>}
     * @memberof ListWorkspaces200Response
     */
    data: Array<Workspace>;
}

/**
 * Check if a given object implements the ListWorkspaces200Response interface.
 */
export function instanceOfListWorkspaces200Response(value: object): value is ListWorkspaces200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListWorkspaces200ResponseFromJSON(json: any): ListWorkspaces200Response {
    return ListWorkspaces200ResponseFromJSONTyped(json, false);
}

export function ListWorkspaces200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkspaces200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': ((json['data'] as Array<any>).map(WorkspaceFromJSON)),
    };
}

export function ListWorkspaces200ResponseToJSON(json: any): ListWorkspaces200Response {
    return ListWorkspaces200ResponseToJSONTyped(json, false);
}

export function ListWorkspaces200ResponseToJSONTyped(value?: ListWorkspaces200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': ((value['data'] as Array<any>).map(WorkspaceToJSON)),
    };
}

