/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListOrganisations403ResponseError } from './ListOrganisations403ResponseError.js';
import {
    ListOrganisations403ResponseErrorFromJSON,
    ListOrganisations403ResponseErrorFromJSONTyped,
    ListOrganisations403ResponseErrorToJSON,
    ListOrganisations403ResponseErrorToJSONTyped,
} from './ListOrganisations403ResponseError.js';

/**
 * Forbidden - Insufficient permissions to access this resource
 * @export
 * @interface ListOrganisations403Response
 */
export interface ListOrganisations403Response {
    [key: string]: any | any;
    /**
     * 
     * @type {ListOrganisations403ResponseError}
     * @memberof ListOrganisations403Response
     */
    error: ListOrganisations403ResponseError;
}

/**
 * Check if a given object implements the ListOrganisations403Response interface.
 */
export function instanceOfListOrganisations403Response(value: object): value is ListOrganisations403Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListOrganisations403ResponseFromJSON(json: any): ListOrganisations403Response {
    return ListOrganisations403ResponseFromJSONTyped(json, false);
}

export function ListOrganisations403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisations403Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': ListOrganisations403ResponseErrorFromJSON(json['error']),
    };
}

export function ListOrganisations403ResponseToJSON(json: any): ListOrganisations403Response {
    return ListOrganisations403ResponseToJSONTyped(json, false);
}

export function ListOrganisations403ResponseToJSONTyped(value?: ListOrganisations403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': ListOrganisations403ResponseErrorToJSON(value['error']),
    };
}

