/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for makeOpportunityFromInsightsAgent
 * @export
 * @interface MakeOpportunityFromInsightsRequest
 */
export interface MakeOpportunityFromInsightsRequest {
    /**
     * List of insight IDs to create opportunity from
     * @type {Array<string>}
     * @memberof MakeOpportunityFromInsightsRequest
     */
    insightIds: Array<string>;
}

/**
 * Check if a given object implements the MakeOpportunityFromInsightsRequest interface.
 */
export function instanceOfMakeOpportunityFromInsightsRequest(value: object): value is MakeOpportunityFromInsightsRequest {
    if (!('insightIds' in value) || value['insightIds'] === undefined) return false;
    return true;
}

export function MakeOpportunityFromInsightsRequestFromJSON(json: any): MakeOpportunityFromInsightsRequest {
    return MakeOpportunityFromInsightsRequestFromJSONTyped(json, false);
}

export function MakeOpportunityFromInsightsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MakeOpportunityFromInsightsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'insightIds': json['insightIds'],
    };
}

export function MakeOpportunityFromInsightsRequestToJSON(json: any): MakeOpportunityFromInsightsRequest {
    return MakeOpportunityFromInsightsRequestToJSONTyped(json, false);
}

export function MakeOpportunityFromInsightsRequestToJSONTyped(value?: MakeOpportunityFromInsightsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'insightIds': value['insightIds'],
    };
}

