/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request body for managing metric relationships
 * @export
 * @interface MetricRelationshipsPayload
 */
export interface MetricRelationshipsPayload {
    /**
     * Array of outcome IDs to associate with the metric
     * @type {Array<string>}
     * @memberof MetricRelationshipsPayload
     */
    outcomeIds?: Array<string>;
}

/**
 * Check if a given object implements the MetricRelationshipsPayload interface.
 */
export function instanceOfMetricRelationshipsPayload(value: object): value is MetricRelationshipsPayload {
    return true;
}

export function MetricRelationshipsPayloadFromJSON(json: any): MetricRelationshipsPayload {
    return MetricRelationshipsPayloadFromJSONTyped(json, false);
}

export function MetricRelationshipsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricRelationshipsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'outcomeIds': json['outcomeIds'] == null ? undefined : json['outcomeIds'],
    };
}

export function MetricRelationshipsPayloadToJSON(json: any): MetricRelationshipsPayload {
    return MetricRelationshipsPayloadToJSONTyped(json, false);
}

export function MetricRelationshipsPayloadToJSONTyped(value?: MetricRelationshipsPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcomeIds': value['outcomeIds'],
    };
}

