/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MockInsightsResponseInner } from './MockInsightsResponseInner.js';
import {
    MockInsightsResponseInnerFromJSON,
    MockInsightsResponseInnerFromJSONTyped,
    MockInsightsResponseInnerToJSON,
    MockInsightsResponseInnerToJSONTyped,
} from './MockInsightsResponseInner.js';

/**
 * Array of mock insights
 * @export
 * @interface MockInsightsResponse
 */
export interface MockInsightsResponse extends Array<MockInsightsResponseInner> {
}

/**
 * Check if a given object implements the MockInsightsResponse interface.
 */
export function instanceOfMockInsightsResponse(value: object): value is MockInsightsResponse {
    return true;
}

export function MockInsightsResponseFromJSON(json: any): MockInsightsResponse {
    return MockInsightsResponseFromJSONTyped(json, false);
}

export function MockInsightsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockInsightsResponse {
    return json;
}

export function MockInsightsResponseToJSON(json: any): MockInsightsResponse {
    return MockInsightsResponseToJSONTyped(json, false);
}

export function MockInsightsResponseToJSONTyped(value?: MockInsightsResponse | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

