/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OnboardingResponseDataOrganisation
 */
export interface OnboardingResponseDataOrganisation {
    /**
     * Unique identifier for the organization
     * @type {string}
     * @memberof OnboardingResponseDataOrganisation
     */
    id: string;
    /**
     * Name of the organization
     * @type {string}
     * @memberof OnboardingResponseDataOrganisation
     */
    name: string;
}

/**
 * Check if a given object implements the OnboardingResponseDataOrganisation interface.
 */
export function instanceOfOnboardingResponseDataOrganisation(value: object): value is OnboardingResponseDataOrganisation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OnboardingResponseDataOrganisationFromJSON(json: any): OnboardingResponseDataOrganisation {
    return OnboardingResponseDataOrganisationFromJSONTyped(json, false);
}

export function OnboardingResponseDataOrganisationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingResponseDataOrganisation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function OnboardingResponseDataOrganisationToJSON(json: any): OnboardingResponseDataOrganisation {
    return OnboardingResponseDataOrganisationToJSONTyped(json, false);
}

export function OnboardingResponseDataOrganisationToJSONTyped(value?: OnboardingResponseDataOrganisation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

