/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for onboarding
 * @export
 * @interface OnboardingPayload
 */
export interface OnboardingPayload {
    /**
     * Name of the organization to create
     * @type {string}
     * @memberof OnboardingPayload
     */
    name: string;
    /**
     * Description of the organization for generating workspace and outcomes
     * @type {string}
     * @memberof OnboardingPayload
     */
    description: string;
}

/**
 * Check if a given object implements the OnboardingPayload interface.
 */
export function instanceOfOnboardingPayload(value: object): value is OnboardingPayload {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function OnboardingPayloadFromJSON(json: any): OnboardingPayload {
    return OnboardingPayloadFromJSONTyped(json, false);
}

export function OnboardingPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function OnboardingPayloadToJSON(json: any): OnboardingPayload {
    return OnboardingPayloadToJSONTyped(json, false);
}

export function OnboardingPayloadToJSONTyped(value?: OnboardingPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

