/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for one-shot onboarding
 * @export
 * @interface OnboardingV2Payload
 */
export interface OnboardingV2Payload {
    /**
     * Text input describing the business or product
     * @type {string}
     * @memberof OnboardingV2Payload
     */
    text: string;
    /**
     * Array of knowledge entity IDs to process
     * @type {Array<string>}
     * @memberof OnboardingV2Payload
     */
    knowledgeIds: Array<string>;
    /**
     * Flag indicating if this is a new product (optional)
     * @type {boolean}
     * @memberof OnboardingV2Payload
     */
    newProduct?: boolean;
}

/**
 * Check if a given object implements the OnboardingV2Payload interface.
 */
export function instanceOfOnboardingV2Payload(value: object): value is OnboardingV2Payload {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('knowledgeIds' in value) || value['knowledgeIds'] === undefined) return false;
    return true;
}

export function OnboardingV2PayloadFromJSON(json: any): OnboardingV2Payload {
    return OnboardingV2PayloadFromJSONTyped(json, false);
}

export function OnboardingV2PayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingV2Payload {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'knowledgeIds': json['knowledgeIds'],
        'newProduct': json['newProduct'] == null ? undefined : json['newProduct'],
    };
}

export function OnboardingV2PayloadToJSON(json: any): OnboardingV2Payload {
    return OnboardingV2PayloadToJSONTyped(json, false);
}

export function OnboardingV2PayloadToJSONTyped(value?: OnboardingV2Payload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'knowledgeIds': value['knowledgeIds'],
        'newProduct': value['newProduct'],
    };
}

