/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrganisationAccountTypeEnum = {
    Hobby: 'HOBBY',
    Professional: 'PROFESSIONAL',
    Team: 'TEAM'
} as const;
export type OrganisationAccountTypeEnum = typeof OrganisationAccountTypeEnum[keyof typeof OrganisationAccountTypeEnum];


export function instanceOfOrganisationAccountTypeEnum(value: any): boolean {
    for (const key in OrganisationAccountTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(OrganisationAccountTypeEnum, key)) {
            if (OrganisationAccountTypeEnum[key as keyof typeof OrganisationAccountTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrganisationAccountTypeEnumFromJSON(json: any): OrganisationAccountTypeEnum {
    return OrganisationAccountTypeEnumFromJSONTyped(json, false);
}

export function OrganisationAccountTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationAccountTypeEnum {
    return json as OrganisationAccountTypeEnum;
}

export function OrganisationAccountTypeEnumToJSON(value?: OrganisationAccountTypeEnum | null): any {
    return value as any;
}

export function OrganisationAccountTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): OrganisationAccountTypeEnum {
    return value as OrganisationAccountTypeEnum;
}

