/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Play Store integration configuration in API response (sanitized)
 * @export
 * @interface PlayStoreResponseConfig
 */
export interface PlayStoreResponseConfig {
    /**
     * Whether the Play Store integration is active
     * @type {boolean}
     * @memberof PlayStoreResponseConfig
     */
    active: boolean;
    /**
     * Name of the app
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    appName: string;
    /**
     * Google Play Store package name
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    appId: string;
    /**
     * User ID who created this integration
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    createdBy: string;
    /**
     * Total number of reviews read so far
     * @type {number}
     * @memberof PlayStoreResponseConfig
     */
    totalReviewsRead: number;
    /**
     * ID of the last review that was read
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    lastReadReviewsId: string | null;
    /**
     * URL of the app icon/image
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    imageUrl: string;
    /**
     * Number of reviews in the last sync
     * @type {number}
     * @memberof PlayStoreResponseConfig
     */
    lastReviewCount: number;
    /**
     * Unix timestamp of the last review read
     * @type {number}
     * @memberof PlayStoreResponseConfig
     */
    lastReadReviewsDate: number | null;
    /**
     * Unix timestamp of the last sync run
     * @type {number}
     * @memberof PlayStoreResponseConfig
     */
    lastRunDate: number | null;
    /**
     * ISO 3166-1 alpha-2 country code (lowercase)
     * @type {string}
     * @memberof PlayStoreResponseConfig
     */
    country: string;
}

/**
 * Check if a given object implements the PlayStoreResponseConfig interface.
 */
export function instanceOfPlayStoreResponseConfig(value: object): value is PlayStoreResponseConfig {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('appName' in value) || value['appName'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('totalReviewsRead' in value) || value['totalReviewsRead'] === undefined) return false;
    if (!('lastReadReviewsId' in value) || value['lastReadReviewsId'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('lastReviewCount' in value) || value['lastReviewCount'] === undefined) return false;
    if (!('lastReadReviewsDate' in value) || value['lastReadReviewsDate'] === undefined) return false;
    if (!('lastRunDate' in value) || value['lastRunDate'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function PlayStoreResponseConfigFromJSON(json: any): PlayStoreResponseConfig {
    return PlayStoreResponseConfigFromJSONTyped(json, false);
}

export function PlayStoreResponseConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayStoreResponseConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'appName': json['app_name'],
        'appId': json['app_id'],
        'createdBy': json['created_by'],
        'totalReviewsRead': json['total_reviews_read'],
        'lastReadReviewsId': json['last_read_reviews_id'],
        'imageUrl': json['image_url'],
        'lastReviewCount': json['last_review_count'],
        'lastReadReviewsDate': json['last_read_reviews_date'],
        'lastRunDate': json['last_run_date'],
        'country': json['country'],
    };
}

export function PlayStoreResponseConfigToJSON(json: any): PlayStoreResponseConfig {
    return PlayStoreResponseConfigToJSONTyped(json, false);
}

export function PlayStoreResponseConfigToJSONTyped(value?: PlayStoreResponseConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'app_name': value['appName'],
        'app_id': value['appId'],
        'created_by': value['createdBy'],
        'total_reviews_read': value['totalReviewsRead'],
        'last_read_reviews_id': value['lastReadReviewsId'],
        'image_url': value['imageUrl'],
        'last_review_count': value['lastReviewCount'],
        'last_read_reviews_date': value['lastReadReviewsDate'],
        'last_run_date': value['lastRunDate'],
        'country': value['country'],
    };
}

