/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PlayStoreResponseConfig } from './PlayStoreResponseConfig.js';
import {
    PlayStoreResponseConfigFromJSON,
    PlayStoreResponseConfigFromJSONTyped,
    PlayStoreResponseConfigToJSON,
    PlayStoreResponseConfigToJSONTyped,
} from './PlayStoreResponseConfig.js';

/**
 * Play Store Reviews integration record
 * @export
 * @interface PlayStoreIntegration
 */
export interface PlayStoreIntegration {
    /**
     * 
     * @type {number}
     * @memberof PlayStoreIntegration
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PlayStoreIntegration
     */
    integrationId: PlayStoreIntegrationIntegrationIdEnum;
    /**
     * 
     * @type {string}
     * @memberof PlayStoreIntegration
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof PlayStoreIntegration
     */
    organisationId: string;
    /**
     * 
     * @type {PlayStoreResponseConfig}
     * @memberof PlayStoreIntegration
     */
    config: PlayStoreResponseConfig;
    /**
     * 
     * @type {Date}
     * @memberof PlayStoreIntegration
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlayStoreIntegration
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const PlayStoreIntegrationIntegrationIdEnum = {
    PlayStoreReviews: 'PLAY_STORE_REVIEWS'
} as const;
export type PlayStoreIntegrationIntegrationIdEnum = typeof PlayStoreIntegrationIntegrationIdEnum[keyof typeof PlayStoreIntegrationIntegrationIdEnum];


/**
 * Check if a given object implements the PlayStoreIntegration interface.
 */
export function instanceOfPlayStoreIntegration(value: object): value is PlayStoreIntegration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PlayStoreIntegrationFromJSON(json: any): PlayStoreIntegration {
    return PlayStoreIntegrationFromJSONTyped(json, false);
}

export function PlayStoreIntegrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayStoreIntegration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'integrationId': json['integrationId'],
        'workspaceId': json['workspaceId'],
        'organisationId': json['organisationId'],
        'config': PlayStoreResponseConfigFromJSON(json['config']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PlayStoreIntegrationToJSON(json: any): PlayStoreIntegration {
    return PlayStoreIntegrationToJSONTyped(json, false);
}

export function PlayStoreIntegrationToJSONTyped(value?: PlayStoreIntegration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'integrationId': value['integrationId'],
        'workspaceId': value['workspaceId'],
        'organisationId': value['organisationId'],
        'config': PlayStoreResponseConfigToJSON(value['config']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

