/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProcessTextProxy200ResponseData
 */
export interface ProcessTextProxy200ResponseData {
    [key: string]: any | any;
    /**
     * Processed text result
     * @type {string}
     * @memberof ProcessTextProxy200ResponseData
     */
    result: string;
    /**
     * AI model used for processing
     * @type {string}
     * @memberof ProcessTextProxy200ResponseData
     */
    model: string;
    /**
     * Time taken to process the request in milliseconds
     * @type {number}
     * @memberof ProcessTextProxy200ResponseData
     */
    processingTime: number;
}

/**
 * Check if a given object implements the ProcessTextProxy200ResponseData interface.
 */
export function instanceOfProcessTextProxy200ResponseData(value: object): value is ProcessTextProxy200ResponseData {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('processingTime' in value) || value['processingTime'] === undefined) return false;
    return true;
}

export function ProcessTextProxy200ResponseDataFromJSON(json: any): ProcessTextProxy200ResponseData {
    return ProcessTextProxy200ResponseDataFromJSONTyped(json, false);
}

export function ProcessTextProxy200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessTextProxy200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'result': json['result'],
        'model': json['model'],
        'processingTime': json['processingTime'],
    };
}

export function ProcessTextProxy200ResponseDataToJSON(json: any): ProcessTextProxy200ResponseData {
    return ProcessTextProxy200ResponseDataToJSONTyped(json, false);
}

export function ProcessTextProxy200ResponseDataToJSONTyped(value?: ProcessTextProxy200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'result': value['result'],
        'model': value['model'],
        'processingTime': value['processingTime'],
    };
}

