/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProcessTextProxy200ResponseData } from './ProcessTextProxy200ResponseData.js';
import {
    ProcessTextProxy200ResponseDataFromJSON,
    ProcessTextProxy200ResponseDataFromJSONTyped,
    ProcessTextProxy200ResponseDataToJSON,
    ProcessTextProxy200ResponseDataToJSONTyped,
} from './ProcessTextProxy200ResponseData.js';

/**
 * Text proxy processing result
 * @export
 * @interface ProcessTextProxy200Response
 */
export interface ProcessTextProxy200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {ProcessTextProxy200ResponseData}
     * @memberof ProcessTextProxy200Response
     */
    data: ProcessTextProxy200ResponseData;
}

/**
 * Check if a given object implements the ProcessTextProxy200Response interface.
 */
export function instanceOfProcessTextProxy200Response(value: object): value is ProcessTextProxy200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProcessTextProxy200ResponseFromJSON(json: any): ProcessTextProxy200Response {
    return ProcessTextProxy200ResponseFromJSONTyped(json, false);
}

export function ProcessTextProxy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessTextProxy200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': ProcessTextProxy200ResponseDataFromJSON(json['data']),
    };
}

export function ProcessTextProxy200ResponseToJSON(json: any): ProcessTextProxy200Response {
    return ProcessTextProxy200ResponseToJSONTyped(json, false);
}

export function ProcessTextProxy200ResponseToJSONTyped(value?: ProcessTextProxy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': ProcessTextProxy200ResponseDataToJSON(value['data']),
    };
}

