/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SimilaritySearchResponseOpportunitiesInnerMetadata } from './SimilaritySearchResponseOpportunitiesInnerMetadata.js';
import {
    SimilaritySearchResponseOpportunitiesInnerMetadataFromJSON,
    SimilaritySearchResponseOpportunitiesInnerMetadataFromJSONTyped,
    SimilaritySearchResponseOpportunitiesInnerMetadataToJSON,
    SimilaritySearchResponseOpportunitiesInnerMetadataToJSONTyped,
} from './SimilaritySearchResponseOpportunitiesInnerMetadata.js';

/**
 * 
 * @export
 * @interface SimilaritySearchResponseOpportunitiesInner
 */
export interface SimilaritySearchResponseOpportunitiesInner {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseOpportunitiesInner
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SimilaritySearchResponseOpportunitiesInner
     */
    score?: number;
    /**
     * 
     * @type {SimilaritySearchResponseOpportunitiesInnerMetadata}
     * @memberof SimilaritySearchResponseOpportunitiesInner
     */
    metadata?: SimilaritySearchResponseOpportunitiesInnerMetadata;
}

/**
 * Check if a given object implements the SimilaritySearchResponseOpportunitiesInner interface.
 */
export function instanceOfSimilaritySearchResponseOpportunitiesInner(value: object): value is SimilaritySearchResponseOpportunitiesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseOpportunitiesInnerFromJSON(json: any): SimilaritySearchResponseOpportunitiesInner {
    return SimilaritySearchResponseOpportunitiesInnerFromJSONTyped(json, false);
}

export function SimilaritySearchResponseOpportunitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseOpportunitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'score': json['score'] == null ? undefined : json['score'],
        'metadata': json['metadata'] == null ? undefined : SimilaritySearchResponseOpportunitiesInnerMetadataFromJSON(json['metadata']),
    };
}

export function SimilaritySearchResponseOpportunitiesInnerToJSON(json: any): SimilaritySearchResponseOpportunitiesInner {
    return SimilaritySearchResponseOpportunitiesInnerToJSONTyped(json, false);
}

export function SimilaritySearchResponseOpportunitiesInnerToJSONTyped(value?: SimilaritySearchResponseOpportunitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'score': value['score'],
        'metadata': SimilaritySearchResponseOpportunitiesInnerMetadataToJSON(value['metadata']),
    };
}

