/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SimilaritySearchResponseOpportunitiesInnerMetadata
 */
export interface SimilaritySearchResponseOpportunitiesInnerMetadata {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseOpportunitiesInnerMetadata
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseOpportunitiesInnerMetadata
     */
    content?: string;
}

/**
 * Check if a given object implements the SimilaritySearchResponseOpportunitiesInnerMetadata interface.
 */
export function instanceOfSimilaritySearchResponseOpportunitiesInnerMetadata(value: object): value is SimilaritySearchResponseOpportunitiesInnerMetadata {
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseOpportunitiesInnerMetadataFromJSON(json: any): SimilaritySearchResponseOpportunitiesInnerMetadata {
    return SimilaritySearchResponseOpportunitiesInnerMetadataFromJSONTyped(json, false);
}

export function SimilaritySearchResponseOpportunitiesInnerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseOpportunitiesInnerMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeId': json['nodeId'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SimilaritySearchResponseOpportunitiesInnerMetadataToJSON(json: any): SimilaritySearchResponseOpportunitiesInnerMetadata {
    return SimilaritySearchResponseOpportunitiesInnerMetadataToJSONTyped(json, false);
}

export function SimilaritySearchResponseOpportunitiesInnerMetadataToJSONTyped(value?: SimilaritySearchResponseOpportunitiesInnerMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodeId': value['nodeId'],
        'content': value['content'],
    };
}

