/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SimilaritySearchResponseInsightsInnerMetadata
 */
export interface SimilaritySearchResponseInsightsInnerMetadata {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseInsightsInnerMetadata
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseInsightsInnerMetadata
     */
    insightId?: string;
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseInsightsInnerMetadata
     */
    content?: string;
}

/**
 * Check if a given object implements the SimilaritySearchResponseInsightsInnerMetadata interface.
 */
export function instanceOfSimilaritySearchResponseInsightsInnerMetadata(value: object): value is SimilaritySearchResponseInsightsInnerMetadata {
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseInsightsInnerMetadataFromJSON(json: any): SimilaritySearchResponseInsightsInnerMetadata {
    return SimilaritySearchResponseInsightsInnerMetadataFromJSONTyped(json, false);
}

export function SimilaritySearchResponseInsightsInnerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseInsightsInnerMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeId': json['nodeId'],
        'insightId': json['insightId'] == null ? undefined : json['insightId'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SimilaritySearchResponseInsightsInnerMetadataToJSON(json: any): SimilaritySearchResponseInsightsInnerMetadata {
    return SimilaritySearchResponseInsightsInnerMetadataToJSONTyped(json, false);
}

export function SimilaritySearchResponseInsightsInnerMetadataToJSONTyped(value?: SimilaritySearchResponseInsightsInnerMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodeId': value['nodeId'],
        'insightId': value['insightId'],
        'content': value['content'],
    };
}

