/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SimilaritySearchResponseOpportunitiesInner } from './SimilaritySearchResponseOpportunitiesInner.js';
import {
    SimilaritySearchResponseOpportunitiesInnerFromJSON,
    SimilaritySearchResponseOpportunitiesInnerFromJSONTyped,
    SimilaritySearchResponseOpportunitiesInnerToJSON,
    SimilaritySearchResponseOpportunitiesInnerToJSONTyped,
} from './SimilaritySearchResponseOpportunitiesInner.js';
import type { SimilaritySearchResponseSolutionsInner } from './SimilaritySearchResponseSolutionsInner.js';
import {
    SimilaritySearchResponseSolutionsInnerFromJSON,
    SimilaritySearchResponseSolutionsInnerFromJSONTyped,
    SimilaritySearchResponseSolutionsInnerToJSON,
    SimilaritySearchResponseSolutionsInnerToJSONTyped,
} from './SimilaritySearchResponseSolutionsInner.js';
import type { SimilaritySearchResponseInsightsInner } from './SimilaritySearchResponseInsightsInner.js';
import {
    SimilaritySearchResponseInsightsInnerFromJSON,
    SimilaritySearchResponseInsightsInnerFromJSONTyped,
    SimilaritySearchResponseInsightsInnerToJSON,
    SimilaritySearchResponseInsightsInnerToJSONTyped,
} from './SimilaritySearchResponseInsightsInner.js';
import type { SimilaritySearchResponseKnowledgeInner } from './SimilaritySearchResponseKnowledgeInner.js';
import {
    SimilaritySearchResponseKnowledgeInnerFromJSON,
    SimilaritySearchResponseKnowledgeInnerFromJSONTyped,
    SimilaritySearchResponseKnowledgeInnerToJSON,
    SimilaritySearchResponseKnowledgeInnerToJSONTyped,
} from './SimilaritySearchResponseKnowledgeInner.js';

/**
 * Similarity search response data
 * @export
 * @interface SimilaritySearchResponse
 */
export interface SimilaritySearchResponse {
    [key: string]: any | any;
    /**
     * Array of matched opportunities
     * @type {Array<SimilaritySearchResponseOpportunitiesInner>}
     * @memberof SimilaritySearchResponse
     */
    opportunities?: Array<SimilaritySearchResponseOpportunitiesInner>;
    /**
     * Array of matched knowledge items
     * @type {Array<SimilaritySearchResponseKnowledgeInner>}
     * @memberof SimilaritySearchResponse
     */
    knowledge?: Array<SimilaritySearchResponseKnowledgeInner>;
    /**
     * Array of matched insights items
     * @type {Array<SimilaritySearchResponseInsightsInner>}
     * @memberof SimilaritySearchResponse
     */
    insights?: Array<SimilaritySearchResponseInsightsInner>;
    /**
     * Array of matched solutions items
     * @type {Array<SimilaritySearchResponseSolutionsInner>}
     * @memberof SimilaritySearchResponse
     */
    solutions?: Array<SimilaritySearchResponseSolutionsInner>;
    /**
     * Total number of results
     * @type {number}
     * @memberof SimilaritySearchResponse
     */
    totalResults: number;
}

/**
 * Check if a given object implements the SimilaritySearchResponse interface.
 */
export function instanceOfSimilaritySearchResponse(value: object): value is SimilaritySearchResponse {
    if (!('totalResults' in value) || value['totalResults'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseFromJSON(json: any): SimilaritySearchResponse {
    return SimilaritySearchResponseFromJSONTyped(json, false);
}

export function SimilaritySearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'opportunities': json['opportunities'] == null ? undefined : ((json['opportunities'] as Array<any>).map(SimilaritySearchResponseOpportunitiesInnerFromJSON)),
        'knowledge': json['knowledge'] == null ? undefined : ((json['knowledge'] as Array<any>).map(SimilaritySearchResponseKnowledgeInnerFromJSON)),
        'insights': json['insights'] == null ? undefined : ((json['insights'] as Array<any>).map(SimilaritySearchResponseInsightsInnerFromJSON)),
        'solutions': json['solutions'] == null ? undefined : ((json['solutions'] as Array<any>).map(SimilaritySearchResponseSolutionsInnerFromJSON)),
        'totalResults': json['totalResults'],
    };
}

export function SimilaritySearchResponseToJSON(json: any): SimilaritySearchResponse {
    return SimilaritySearchResponseToJSONTyped(json, false);
}

export function SimilaritySearchResponseToJSONTyped(value?: SimilaritySearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'opportunities': value['opportunities'] == null ? undefined : ((value['opportunities'] as Array<any>).map(SimilaritySearchResponseOpportunitiesInnerToJSON)),
        'knowledge': value['knowledge'] == null ? undefined : ((value['knowledge'] as Array<any>).map(SimilaritySearchResponseKnowledgeInnerToJSON)),
        'insights': value['insights'] == null ? undefined : ((value['insights'] as Array<any>).map(SimilaritySearchResponseInsightsInnerToJSON)),
        'solutions': value['solutions'] == null ? undefined : ((value['solutions'] as Array<any>).map(SimilaritySearchResponseSolutionsInnerToJSON)),
        'totalResults': value['totalResults'],
    };
}

