/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SimilaritySearchResponseInsightsInnerMetadata } from './SimilaritySearchResponseInsightsInnerMetadata.js';
import {
    SimilaritySearchResponseInsightsInnerMetadataFromJSON,
    SimilaritySearchResponseInsightsInnerMetadataFromJSONTyped,
    SimilaritySearchResponseInsightsInnerMetadataToJSON,
    SimilaritySearchResponseInsightsInnerMetadataToJSONTyped,
} from './SimilaritySearchResponseInsightsInnerMetadata.js';

/**
 * 
 * @export
 * @interface SimilaritySearchResponseInsightsInner
 */
export interface SimilaritySearchResponseInsightsInner {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseInsightsInner
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SimilaritySearchResponseInsightsInner
     */
    score?: number;
    /**
     * 
     * @type {SimilaritySearchResponseInsightsInnerMetadata}
     * @memberof SimilaritySearchResponseInsightsInner
     */
    metadata?: SimilaritySearchResponseInsightsInnerMetadata;
}

/**
 * Check if a given object implements the SimilaritySearchResponseInsightsInner interface.
 */
export function instanceOfSimilaritySearchResponseInsightsInner(value: object): value is SimilaritySearchResponseInsightsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseInsightsInnerFromJSON(json: any): SimilaritySearchResponseInsightsInner {
    return SimilaritySearchResponseInsightsInnerFromJSONTyped(json, false);
}

export function SimilaritySearchResponseInsightsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseInsightsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'score': json['score'] == null ? undefined : json['score'],
        'metadata': json['metadata'] == null ? undefined : SimilaritySearchResponseInsightsInnerMetadataFromJSON(json['metadata']),
    };
}

export function SimilaritySearchResponseInsightsInnerToJSON(json: any): SimilaritySearchResponseInsightsInner {
    return SimilaritySearchResponseInsightsInnerToJSONTyped(json, false);
}

export function SimilaritySearchResponseInsightsInnerToJSONTyped(value?: SimilaritySearchResponseInsightsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'score': value['score'],
        'metadata': SimilaritySearchResponseInsightsInnerMetadataToJSON(value['metadata']),
    };
}

