/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SimilaritySearchResponseKnowledgeInnerMetadata
 */
export interface SimilaritySearchResponseKnowledgeInnerMetadata {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseKnowledgeInnerMetadata
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseKnowledgeInnerMetadata
     */
    content?: string;
}

/**
 * Check if a given object implements the SimilaritySearchResponseKnowledgeInnerMetadata interface.
 */
export function instanceOfSimilaritySearchResponseKnowledgeInnerMetadata(value: object): value is SimilaritySearchResponseKnowledgeInnerMetadata {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseKnowledgeInnerMetadataFromJSON(json: any): SimilaritySearchResponseKnowledgeInnerMetadata {
    return SimilaritySearchResponseKnowledgeInnerMetadataFromJSONTyped(json, false);
}

export function SimilaritySearchResponseKnowledgeInnerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseKnowledgeInnerMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SimilaritySearchResponseKnowledgeInnerMetadataToJSON(json: any): SimilaritySearchResponseKnowledgeInnerMetadata {
    return SimilaritySearchResponseKnowledgeInnerMetadataToJSONTyped(json, false);
}

export function SimilaritySearchResponseKnowledgeInnerMetadataToJSONTyped(value?: SimilaritySearchResponseKnowledgeInnerMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
    };
}

