/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SimilaritySearchResponseSolutionsInnerMetadata
 */
export interface SimilaritySearchResponseSolutionsInnerMetadata {
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseSolutionsInnerMetadata
     */
    nodeId: string;
    /**
     * Solution status
     * @type {string}
     * @memberof SimilaritySearchResponseSolutionsInnerMetadata
     */
    status: SimilaritySearchResponseSolutionsInnerMetadataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof SimilaritySearchResponseSolutionsInnerMetadata
     */
    content?: string;
}


/**
 * @export
 */
export const SimilaritySearchResponseSolutionsInnerMetadataStatusEnum = {
    Backlog: 'Backlog',
    New: 'New',
    Planned: 'Planned',
    InDevelopment: 'InDevelopment',
    Complete: 'Complete',
    Cancelled: 'Cancelled',
    Live: 'Live'
} as const;
export type SimilaritySearchResponseSolutionsInnerMetadataStatusEnum = typeof SimilaritySearchResponseSolutionsInnerMetadataStatusEnum[keyof typeof SimilaritySearchResponseSolutionsInnerMetadataStatusEnum];


/**
 * Check if a given object implements the SimilaritySearchResponseSolutionsInnerMetadata interface.
 */
export function instanceOfSimilaritySearchResponseSolutionsInnerMetadata(value: object): value is SimilaritySearchResponseSolutionsInnerMetadata {
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SimilaritySearchResponseSolutionsInnerMetadataFromJSON(json: any): SimilaritySearchResponseSolutionsInnerMetadata {
    return SimilaritySearchResponseSolutionsInnerMetadataFromJSONTyped(json, false);
}

export function SimilaritySearchResponseSolutionsInnerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilaritySearchResponseSolutionsInnerMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeId': json['nodeId'],
        'status': json['status'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SimilaritySearchResponseSolutionsInnerMetadataToJSON(json: any): SimilaritySearchResponseSolutionsInnerMetadata {
    return SimilaritySearchResponseSolutionsInnerMetadataToJSONTyped(json, false);
}

export function SimilaritySearchResponseSolutionsInnerMetadataToJSONTyped(value?: SimilaritySearchResponseSolutionsInnerMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodeId': value['nodeId'],
        'status': value['status'],
        'content': value['content'],
    };
}

