/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SingleKnowledgeResponseData } from './SingleKnowledgeResponseData.js';
import {
    SingleKnowledgeResponseDataFromJSON,
    SingleKnowledgeResponseDataFromJSONTyped,
    SingleKnowledgeResponseDataToJSON,
    SingleKnowledgeResponseDataToJSONTyped,
} from './SingleKnowledgeResponseData.js';

/**
 * Response containing a single knowledge
 * @export
 * @interface SingleKnowledgeResponse
 */
export interface SingleKnowledgeResponse {
    /**
     * 
     * @type {SingleKnowledgeResponseData}
     * @memberof SingleKnowledgeResponse
     */
    data: SingleKnowledgeResponseData;
}

/**
 * Check if a given object implements the SingleKnowledgeResponse interface.
 */
export function instanceOfSingleKnowledgeResponse(value: object): value is SingleKnowledgeResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SingleKnowledgeResponseFromJSON(json: any): SingleKnowledgeResponse {
    return SingleKnowledgeResponseFromJSONTyped(json, false);
}

export function SingleKnowledgeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleKnowledgeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SingleKnowledgeResponseDataFromJSON(json['data']),
    };
}

export function SingleKnowledgeResponseToJSON(json: any): SingleKnowledgeResponse {
    return SingleKnowledgeResponseToJSONTyped(json, false);
}

export function SingleKnowledgeResponseToJSONTyped(value?: SingleKnowledgeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SingleKnowledgeResponseDataToJSON(value['data']),
    };
}

