/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InsightResponse } from './InsightResponse.js';
import {
    InsightResponseFromJSON,
    InsightResponseFromJSONTyped,
    InsightResponseToJSON,
    InsightResponseToJSONTyped,
} from './InsightResponse.js';

/**
 * 
 * @export
 * @interface SubmitFeedback201Response
 */
export interface SubmitFeedback201Response {
    [key: string]: any | any;
    /**
     * 
     * @type {InsightResponse}
     * @memberof SubmitFeedback201Response
     */
    data: InsightResponse;
}

/**
 * Check if a given object implements the SubmitFeedback201Response interface.
 */
export function instanceOfSubmitFeedback201Response(value: object): value is SubmitFeedback201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubmitFeedback201ResponseFromJSON(json: any): SubmitFeedback201Response {
    return SubmitFeedback201ResponseFromJSONTyped(json, false);
}

export function SubmitFeedback201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitFeedback201Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': InsightResponseFromJSON(json['data']),
    };
}

export function SubmitFeedback201ResponseToJSON(json: any): SubmitFeedback201Response {
    return SubmitFeedback201ResponseToJSONTyped(json, false);
}

export function SubmitFeedback201ResponseToJSONTyped(value?: SubmitFeedback201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': InsightResponseToJSON(value['data']),
    };
}

