/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Token exchange response
 * @export
 * @interface TokenExchangeResponse
 */
export interface TokenExchangeResponse {
    /**
     * JWT access token for authenticating with the Squad API
     * @type {string}
     * @memberof TokenExchangeResponse
     */
    accessToken: string;
    /**
     * Token type
     * @type {string}
     * @memberof TokenExchangeResponse
     */
    tokenType: TokenExchangeResponseTokenTypeEnum;
    /**
     * Token lifetime in seconds
     * @type {number}
     * @memberof TokenExchangeResponse
     */
    expiresIn: number;
}


/**
 * @export
 */
export const TokenExchangeResponseTokenTypeEnum = {
    Bearer: 'Bearer'
} as const;
export type TokenExchangeResponseTokenTypeEnum = typeof TokenExchangeResponseTokenTypeEnum[keyof typeof TokenExchangeResponseTokenTypeEnum];


/**
 * Check if a given object implements the TokenExchangeResponse interface.
 */
export function instanceOfTokenExchangeResponse(value: object): value is TokenExchangeResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function TokenExchangeResponseFromJSON(json: any): TokenExchangeResponse {
    return TokenExchangeResponseFromJSONTyped(json, false);
}

export function TokenExchangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenExchangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
    };
}

export function TokenExchangeResponseToJSON(json: any): TokenExchangeResponse {
    return TokenExchangeResponseToJSONTyped(json, false);
}

export function TokenExchangeResponseToJSONTyped(value?: TokenExchangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
    };
}

