/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating a topic
 * @export
 * @interface UpdateTopicPayload
 */
export interface UpdateTopicPayload {
    /**
     * Title of the topic
     * @type {string}
     * @memberof UpdateTopicPayload
     */
    title?: string;
    /**
     * Description of the topic
     * @type {string}
     * @memberof UpdateTopicPayload
     */
    description?: string;
    /**
     * List of opportunity IDs associated with the topic
     * @type {Array<string>}
     * @memberof UpdateTopicPayload
     */
    opportunityIds?: Array<string>;
    /**
     * List of insight IDs associated with the topic
     * @type {Array<string>}
     * @memberof UpdateTopicPayload
     */
    insightIds?: Array<string>;
}

/**
 * Check if a given object implements the UpdateTopicPayload interface.
 */
export function instanceOfUpdateTopicPayload(value: object): value is UpdateTopicPayload {
    return true;
}

export function UpdateTopicPayloadFromJSON(json: any): UpdateTopicPayload {
    return UpdateTopicPayloadFromJSONTyped(json, false);
}

export function UpdateTopicPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTopicPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'opportunityIds': json['opportunityIds'] == null ? undefined : json['opportunityIds'],
        'insightIds': json['insightIds'] == null ? undefined : json['insightIds'],
    };
}

export function UpdateTopicPayloadToJSON(json: any): UpdateTopicPayload {
    return UpdateTopicPayloadToJSONTyped(json, false);
}

export function UpdateTopicPayloadToJSONTyped(value?: UpdateTopicPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'opportunityIds': value['opportunityIds'],
        'insightIds': value['insightIds'],
    };
}

