/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating an integration
 * @export
 * @interface UpdateIntegrationPayload
 */
export interface UpdateIntegrationPayload {
    /**
     * 
     * @type {object}
     * @memberof UpdateIntegrationPayload
     */
    config: object;
}

/**
 * Check if a given object implements the UpdateIntegrationPayload interface.
 */
export function instanceOfUpdateIntegrationPayload(value: object): value is UpdateIntegrationPayload {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function UpdateIntegrationPayloadFromJSON(json: any): UpdateIntegrationPayload {
    return UpdateIntegrationPayloadFromJSONTyped(json, false);
}

export function UpdateIntegrationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIntegrationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
    };
}

export function UpdateIntegrationPayloadToJSON(json: any): UpdateIntegrationPayload {
    return UpdateIntegrationPayloadToJSONTyped(json, false);
}

export function UpdateIntegrationPayloadToJSONTyped(value?: UpdateIntegrationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

