/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateSolutionPayloadRefinementLogInner
 */
export interface UpdateSolutionPayloadRefinementLogInner {
    /**
     * Unique identifier for the log entry
     * @type {string}
     * @memberof UpdateSolutionPayloadRefinementLogInner
     */
    id: string;
    /**
     * Role of the entity making the log entry
     * @type {string}
     * @memberof UpdateSolutionPayloadRefinementLogInner
     */
    role: UpdateSolutionPayloadRefinementLogInnerRoleEnum;
    /**
     * Content of the log entry
     * @type {string}
     * @memberof UpdateSolutionPayloadRefinementLogInner
     */
    content: string;
}


/**
 * @export
 */
export const UpdateSolutionPayloadRefinementLogInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type UpdateSolutionPayloadRefinementLogInnerRoleEnum = typeof UpdateSolutionPayloadRefinementLogInnerRoleEnum[keyof typeof UpdateSolutionPayloadRefinementLogInnerRoleEnum];


/**
 * Check if a given object implements the UpdateSolutionPayloadRefinementLogInner interface.
 */
export function instanceOfUpdateSolutionPayloadRefinementLogInner(value: object): value is UpdateSolutionPayloadRefinementLogInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateSolutionPayloadRefinementLogInnerFromJSON(json: any): UpdateSolutionPayloadRefinementLogInner {
    return UpdateSolutionPayloadRefinementLogInnerFromJSONTyped(json, false);
}

export function UpdateSolutionPayloadRefinementLogInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSolutionPayloadRefinementLogInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'content': json['content'],
    };
}

export function UpdateSolutionPayloadRefinementLogInnerToJSON(json: any): UpdateSolutionPayloadRefinementLogInner {
    return UpdateSolutionPayloadRefinementLogInnerToJSONTyped(json, false);
}

export function UpdateSolutionPayloadRefinementLogInnerToJSONTyped(value?: UpdateSolutionPayloadRefinementLogInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
    };
}

