/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateStrategyDocumentPayloadData
 */
export interface UpdateStrategyDocumentPayloadData {
    /**
     * Strategy document report
     * @type {string}
     * @memberof UpdateStrategyDocumentPayloadData
     */
    report: string;
}

/**
 * Check if a given object implements the UpdateStrategyDocumentPayloadData interface.
 */
export function instanceOfUpdateStrategyDocumentPayloadData(value: object): value is UpdateStrategyDocumentPayloadData {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function UpdateStrategyDocumentPayloadDataFromJSON(json: any): UpdateStrategyDocumentPayloadData {
    return UpdateStrategyDocumentPayloadDataFromJSONTyped(json, false);
}

export function UpdateStrategyDocumentPayloadDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStrategyDocumentPayloadData {
    if (json == null) {
        return json;
    }
    return {
        
        'report': json['report'],
    };
}

export function UpdateStrategyDocumentPayloadDataToJSON(json: any): UpdateStrategyDocumentPayloadData {
    return UpdateStrategyDocumentPayloadDataToJSONTyped(json, false);
}

export function UpdateStrategyDocumentPayloadDataToJSONTyped(value?: UpdateStrategyDocumentPayloadData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': value['report'],
    };
}

