/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UpdateStrategyDocumentPayloadData } from './UpdateStrategyDocumentPayloadData.js';
import {
    UpdateStrategyDocumentPayloadDataFromJSON,
    UpdateStrategyDocumentPayloadDataFromJSONTyped,
    UpdateStrategyDocumentPayloadDataToJSON,
    UpdateStrategyDocumentPayloadDataToJSONTyped,
} from './UpdateStrategyDocumentPayloadData.js';

/**
 * Request schema for updating a strategy document
 * @export
 * @interface UpdateStrategyDocumentPayload
 */
export interface UpdateStrategyDocumentPayload {
    [key: string]: any | any;
    /**
     * 
     * @type {UpdateStrategyDocumentPayloadData}
     * @memberof UpdateStrategyDocumentPayload
     */
    data: UpdateStrategyDocumentPayloadData;
}

/**
 * Check if a given object implements the UpdateStrategyDocumentPayload interface.
 */
export function instanceOfUpdateStrategyDocumentPayload(value: object): value is UpdateStrategyDocumentPayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UpdateStrategyDocumentPayloadFromJSON(json: any): UpdateStrategyDocumentPayload {
    return UpdateStrategyDocumentPayloadFromJSONTyped(json, false);
}

export function UpdateStrategyDocumentPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStrategyDocumentPayload {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'data': UpdateStrategyDocumentPayloadDataFromJSON(json['data']),
    };
}

export function UpdateStrategyDocumentPayloadToJSON(json: any): UpdateStrategyDocumentPayload {
    return UpdateStrategyDocumentPayloadToJSONTyped(json, false);
}

export function UpdateStrategyDocumentPayloadToJSONTyped(value?: UpdateStrategyDocumentPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'data': UpdateStrategyDocumentPayloadDataToJSON(value['data']),
    };
}

