/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.8.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WhoAmIResponseDataWorkspace
 */
export interface WhoAmIResponseDataWorkspace {
    /**
     * Workspace ID
     * @type {string}
     * @memberof WhoAmIResponseDataWorkspace
     */
    id: string;
    /**
     * Workspace name
     * @type {string}
     * @memberof WhoAmIResponseDataWorkspace
     */
    name: string;
}

/**
 * Check if a given object implements the WhoAmIResponseDataWorkspace interface.
 */
export function instanceOfWhoAmIResponseDataWorkspace(value: object): value is WhoAmIResponseDataWorkspace {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WhoAmIResponseDataWorkspaceFromJSON(json: any): WhoAmIResponseDataWorkspace {
    return WhoAmIResponseDataWorkspaceFromJSONTyped(json, false);
}

export function WhoAmIResponseDataWorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhoAmIResponseDataWorkspace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function WhoAmIResponseDataWorkspaceToJSON(json: any): WhoAmIResponseDataWorkspace {
    return WhoAmIResponseDataWorkspaceToJSONTyped(json, false);
}

export function WhoAmIResponseDataWorkspaceToJSONTyped(value?: WhoAmIResponseDataWorkspace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

