# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed by ncipollo/release-action

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn bun:build # Creates files in ./bin/

      - name: Make binaries executable
        run: chmod +x ./bin/*

      - name: Create Release and Upload Binaries
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/*" # Correct glob pattern for the binaries
          token: ${{ secrets.GITHUB_TOKEN }}
          # By default, this action doesn't upload source code archives
